xbps-triggers: system-accounts: add support to specify gid in system_groups.

diff --git a/srcpkgs/xbps-triggers/files/system-accounts b/srcpkgs/xbps-triggers/files/system-accounts
--- a/srcpkgs/xbps-triggers/files/system-accounts
+++ b/srcpkgs/xbps-triggers/files/system-accounts
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/sh
 #
 # (Un)registers systems accounts (users/groups).
 #
@@ -14,8 +14,6 @@ PKGNAME="$3"
 VERSION="$4"
 UPDATE="$5"
 
-export PATH="$PATH:/usr/local/bin"
-
 USERADD=usr/sbin/useradd
 USERDEL=usr/sbin/userdel
 GROUPADD=usr/sbin/groupadd
@@ -23,16 +21,26 @@ GROUPDEL=usr/sbin/groupdel
 PASSWD=usr/bin/passwd
 GETENT=usr/bin/getent
 
-group_add()
-{
-	local grp="$1"
+group_add() {
+	local _grname _gid use_gid
 
-	if ! $GETENT group ${grp} >/dev/null; then
-		$GROUPADD -r ${grp} >/dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			echo "Created ${grp} system group."
+	_grname="${1%:*}"
+	_gid="${1#*:}"
+
+	if [ "${_gid}" != "${_grname}" ]; then
+		use_gid="gid ${_gid}"
+	fi
+
+	if ! $GETENT group ${_grname} >/dev/null; then
+		if [ -n "$use_gid" ]; then
+			$GROUPADD -r ${_grname} -g ${_gid} >/dev/null 2>&1
 		else
-			echo "Failed to create ${grp} system group!"
+			$GROUPADD -r ${_grname} >/dev/null 2>&1
+		fi
+		if [ $? -eq 0 ]; then
+			echo "Created ${grp} ($use_gid) system group."
+		else
+			echo "Failed to create ${grp} ($use_gid) system group!"
 			exit 1
 		fi
 	fi
