spotify: correctly download client on i686, improve error reporting

diff --git a/srcpkgs/spotify/INSTALL b/srcpkgs/spotify/INSTALL
--- a/srcpkgs/spotify/INSTALL
+++ b/srcpkgs/spotify/INSTALL
@@ -13,18 +13,19 @@ if test "$ACTION" = "post"; then
 	. /usr/share/spotify/pkgdata
 	mkdir -p "$_BUILDDIR"
 	(
+		set -e
 		cd "$_BUILDDIR"
 		xbps-uhelper fetch "http://repository.spotify.com/pool/non-free/s/spotify/spotify-client_${SVERSION}.deb"
 		echo "${SCHECKSUM}  spotify-client_${SVERSION}.deb" >checksum
-		sha256sum -c checksum || exit 1
+		sha256sum -c checksum
 		ar x "spotify-client_${SVERSION}.deb"
-		[ -f data.tar.gz ] && tar xzf data.tar.gz 2>/dev/null
-		[ -f data.tar.xz ] && tar xJf data.tar.xz 2>/dev/null
-	) || {
-		echo Error while extracting;
+		tar -xf data.tar.*
+	)
+	if [ $? -ne 0 ] ; then
+		echo "Failed downloading spotify client"
 		rm -r "$_BUILDDIR";
 		exit 1;
-	}
+	fi
 	mkdir -p /usr/share/licenses/spotify
 	mv "${_BUILDDIR}/usr/share/doc/spotify-client/copyright" /usr/share/licenses/spotify/
 
