xbps-src: repair 'bootstrap' target on musl hosts, improvements.
- `xbps-src bootstrap` now works in musl hosts.
- `xbps-src bootstrap` will only use local repos, never remote.
- multiple cleanups in xbps-src, simplify code.

Close https://github.com/void-linux/void-packages/pull/11052

diff --git a/xbps-src b/xbps-src
--- a/xbps-src
+++ b/xbps-src
@@ -1,8 +1,6 @@
 #!/bin/bash
 # vim: set ts=4 sw=4 et:
 
-readonly PROGNAME="${0##*/}"
-
 print_cross_targets() {
     local f
     for f in common/cross-profiles/*.sh; do
@@ -230,20 +228,21 @@ check_reqhost_utils() {
     [ -n "$broken" ] && exit 1
 }
 
-check_config_vars() {
-    if [ -s "$XBPS_CONFIG_FILE" ]; then
-        . $XBPS_CONFIG_FILE &>/dev/null
-    fi
-    if [ -z "$XBPS_MASTERDIR" ]; then
-        export XBPS_MASTERDIR="${XBPS_DISTDIR}/masterdir"
-    fi
-    if [ -z "$XBPS_HOSTDIR" ]; then
-        export XBPS_HOSTDIR="${XBPS_DISTDIR}/hostdir"
-        [ ! -d $XBPS_HOSTDIR ] && mkdir -p $XBPS_HOSTDIR
-    fi
-    if [ -d "$XBPS_MASTERDIR" -a ! -w "$XBPS_MASTERDIR" ]; then
-        echo "ERROR: not enough perms for masterdir $XBPS_MASTERDIR."
-        exit 1
+check_native_arch() {
+    if [ "$CHROOT_READY" ]; then
+        if [ -s $XBPS_MASTERDIR/.xbps_chroot_init ]; then
+            export XBPS_ARCH=$(cat $XBPS_MASTERDIR/.xbps_chroot_init)
+        else
+            export XBPS_ARCH=$(uname -m)
+        fi
+    else
+        LDD=$(ldd --version 2>&1|head -1)
+        if [[ $LDD == *musl* ]]; then
+            export XBPS_ARCH=${XBPS_MACHINE%-musl}-musl
+        else
+            # XBPS_ARCH == $(uname -m)
+            export XBPS_ARCH=$(uname -m)
+        fi
     fi
 }
 
@@ -290,39 +289,36 @@ check_build_requirements() {
     fi
 }
 
+chroot_check() {
+    if [ -f $XBPS_MASTERDIR/.xbps_chroot_init -o "$XBPS_CHROOT_CMD" = "ethereal" ]; then
+        export CHROOT_READY=1
+    fi
+}
+
 install_bbootstrap() {
-    [ -n "$CHROOT_READY" ] && return
-    if [ "$1" = "bootstrap" ]; then
-        unset XBPS_TARGET_PKG XBPS_INSTALL_ARGS
-    else
-        XBPS_TARGET_PKG="$1"
-    fi
-    if [ -n "$XBPS_SKIP_REMOTEREPOS" ]; then
-        unset XBPS_INSTALL_ARGS
-    fi
+    local TARGET_ARCH=$1
+
+    [ "$CHROOT_READY" ] && return
+    [ "$XBPS_SKIP_REMOTEREPOS" -o -z "$TARGET_ARCH" ] &&  unset XBPS_INSTALL_ARGS
+
     # binary bootstrap
     msg_normal "Installing bootstrap from binary package repositories...\n"
-    # XBPS_TARGET_PKG == arch
-    if [ -n "$XBPS_TARGET_PKG" ]; then
-        _bootstrap_arch="env XBPS_TARGET_ARCH=$XBPS_TARGET_PKG"
-        if [ "${XBPS_TARGET_PKG}" != "${XBPS_TARGET_PKG#*-}" ]; then
-            _subarch="-${XBPS_TARGET_PKG#*-}"
-        fi
-    fi
     mkdir -p $XBPS_MASTERDIR/var/db/xbps/keys
-    cd $XBPS_MASTERDIR
     cp -f $XBPS_COMMONDIR/repo-keys/*.plist $XBPS_MASTERDIR/var/db/xbps/keys
-    ${_bootstrap_arch} $XBPS_INSTALL_CMD ${XBPS_INSTALL_ARGS:+-S $XBPS_INSTALL_ARGS} -y base-chroot${_subarch}
+    # binary-bootstrap, use remote and then local.
+    [ "$TARGET_ARCH" ] && export XBPS_ARCH=$TARGET_ARCH
+    $XBPS_INSTALL_CMD ${XBPS_INSTALL_ARGS:+-S $XBPS_INSTALL_ARGS} -y base-chroot
     if [ $? -ne 0 ]; then
         msg_error "Failed to install bootstrap packages!\n"
     fi
     # Reconfigure base-files to create dirs/symlinks.
-    if xbps-query -r $XBPS_MASTERDIR base-files &>/dev/null; then
-        XBPS_ARCH=$XBPS_TARGET_PKG xbps-reconfigure -r $XBPS_MASTERDIR -f base-files &>/dev/null
+    if $XBPS_QUERY_CMD base-files &>/dev/null; then
+        $XBPS_RECONFIGURE_CMD -f base-files &>/dev/null
     fi
 
     msg_normal "Installed bootstrap successfully!\n"
-    chroot_prepare $XBPS_TARGET_PKG || msg_error "Failed to initialize chroot!\n"
+    chroot_prepare $TARGET_ARCH || msg_error "Failed to initialize chroot!\n"
+    chroot_init
     chroot_check
     chroot_handler clean
 }
@@ -334,8 +330,8 @@ reconfigure_bootstrap_pkgs() {
     # Reconfigure ca-certificates.
     msg_normal "Reconfiguring bootstrap packages...\n"
     for f in ${pkgs}; do
-        if xbps-query $f &>/dev/null; then
-            xbps-reconfigure -f $f
+        if $XBPS_QUERY_CMD $f &>/dev/null; then
+            $XBPS_RECONFIGURE_CMD -f $f
         fi
     done
     touch -f $statefile
@@ -376,9 +372,7 @@ exit_func() {
     if [ -n "$sourcepkg" ]; then
         remove_pkg $XBPS_CROSS_BUILD
     fi
-    if [ -z "$IN_CHROOT" ]; then
-        msg_red "xbps-src: a failure has ocurred! exiting...\n"
-    fi
+    msg_red "xbps-src: a failure has ocurred! exiting...\n"
     exit 2
 }
 
@@ -416,14 +410,25 @@ setup_distfiles_mirror() {
     done
 }
 
-readonly XBPS_VERSION_REQ="0.46"
-readonly XBPS_VERSION=$(xbps-uhelper -V|awk '{print $2}')
-readonly XBPS_SRC_VERSION="113"
-export XBPS_MACHINE=$(xbps-uhelper arch)
-
 #
 # main()
 #
+readonly PROGNAME="${0##*/}"
+readonly XBPS_VERSION_REQ="0.46"
+XBPS_VERSION=$(xbps-uhelper -V)
+XBPS_VERSION=${XBPS_VERSION%%API*}
+XBPS_VERSION=${XBPS_VERSION##*:}
+readonly XBPS_SRC_VERSION="113"
+
+# Required utilities in host system for the bootstrap target.
+readonly REQHOST_UTILS_BOOTSTRAP="make awk bash bison sed gcc g++ msgfmt makeinfo \
+    perl tar xz gzip bzip2 patch flex automake libtool pkg-config"
+
+# Required utilities in host system for chroot ops.
+readonly REQHOST_UTILS="xbps-install xbps-query xbps-rindex xbps-uhelper \
+    xbps-reconfigure xbps-remove xbps-create xbps-uchroot xbps-uunshare \
+    xbps-uchroot"
+
 XBPS_OPTIONS=
 XBPS_OPTSTRING="1a:CEfgGhH:iIj:Lm:No:qQr:tV"
 
@@ -460,19 +465,12 @@ shift $(($OPTIND - 1))
 
 [ $# -eq 0 ] && usage && exit 1
 
+# sane umask
 umask 022
 
 #
 # Check for required utilities in host system.
 #
-# Required utilities in host system for the bootstrap target.
-readonly REQHOST_UTILS_BOOTSTRAP="make gawk bash bison sed gcc g++ msgfmt makeinfo \
-    perl tar xz gzip bzip2 patch flex automake libtool pkg-config"
-
-# Required utilities in host system for chroot ops.
-readonly REQHOST_UTILS="xbps-install xbps-query xbps-rindex xbps-uhelper \
-    xbps-reconfigure xbps-remove xbps-create xbps-uchroot xbps-uunshare"
-
 check_reqhost_utils
 
 # Try using chroot-git then git from the host system
@@ -487,6 +485,12 @@ fi
 
 readonly XBPS_GIT_CMD
 
+# ... at this point xbps-uhelper is in PATH.
+readonly XBPS_MACHINE=$(xbps-uhelper -C /dev/null arch)
+
+#
+# Read configuration file and set up XBPS_DISTDIR and XBPS_CONFIG_FILE
+#
 if [ -n "$IN_CHROOT" ]; then
     readonly XBPS_CONFIG_FILE=/etc/xbps/xbps-src.conf
     readonly XBPS_DISTDIR=/void-packages
@@ -510,11 +514,17 @@ else
         . $XBPS_CONFIG_FILE
     fi
 fi
-
-#
-# Check configuration vars before anyting else, and set defaults vars.
-#
-check_config_vars
+if [ -z "$XBPS_MASTERDIR" ]; then
+    export XBPS_MASTERDIR="${XBPS_DISTDIR}/masterdir"
+fi
+if [ -d "$XBPS_MASTERDIR" -a ! -w "$XBPS_MASTERDIR" ]; then
+    echo "ERROR: not enough perms for masterdir $XBPS_MASTERDIR."
+    exit 1
+fi
+if [ -z "$XBPS_HOSTDIR" ]; then
+    export XBPS_HOSTDIR="${XBPS_DISTDIR}/hostdir"
+    [ ! -d $XBPS_HOSTDIR ] && mkdir -p $XBPS_HOSTDIR
+fi
 
 if [ -n "$XBPS_HOSTDIR" ]; then
     export XBPS_REPOSITORY=$XBPS_HOSTDIR/binpkgs
@@ -527,41 +537,35 @@ if [ -n "$IN_CHROOT" ]; then
     readonly XBPS_UHELPER_CMD="xbps-uhelper"
     readonly XBPS_INSTALL_CMD="xbps-install"
     readonly XBPS_QUERY_CMD="xbps-query"
-    readonly XBPS_RINDEX_CMD="xbps-rindex"
     readonly XBPS_RECONFIGURE_CMD="xbps-reconfigure"
     readonly XBPS_REMOVE_CMD="xbps-remove"
     readonly XBPS_SRCPKGDIR=/void-packages/srcpkgs
     readonly XBPS_COMMONDIR=/void-packages/common
     readonly XBPS_DESTDIR=/destdir
     readonly XBPS_BUILDDIR=/builddir
-    readonly XBPS_SHUTILSDIR=$XBPS_COMMONDIR/xbps-src/shutils
-    readonly XBPS_TRIGGERSDIR=$XBPS_SRCPKGDIR/xbps-triggers/files
-    readonly XBPS_CROSSPFDIR=$XBPS_COMMONDIR/cross-profiles
-    readonly XBPS_BUILDSTYLEDIR=$XBPS_COMMONDIR/build-style
-    readonly XBPS_LIBEXECDIR=$XBPS_COMMONDIR/xbps-src/libexec
-    readonly XBPS_BUILDHELPERDIR=$XBPS_COMMONDIR/build-helper
 else
     readonly XBPS_UHELPER_CMD="xbps-uhelper -r $XBPS_MASTERDIR"
-    readonly XBPS_INSTALL_CMD="xbps-install -C /dev/null -c $XBPS_HOSTDIR/repocache --repository=$XBPS_REPOSITORY -r $XBPS_MASTERDIR"
-    readonly XBPS_QUERY_CMD="xbps-query -C /dev/null -c $XBPS_HOSTDIR/repocache -i --repository=$XBPS_REPOSITORY -r $XBPS_MASTERDIR"
-    readonly XBPS_RINDEX_CMD="xbps-rindex"
+    readonly XBPS_INSTALL_CMD="xbps-install -c $XBPS_HOSTDIR/repocache --repository=$XBPS_REPOSITORY -r $XBPS_MASTERDIR"
+    readonly XBPS_QUERY_CMD="xbps-query -c $XBPS_HOSTDIR/repocache --repository=$XBPS_REPOSITORY -r $XBPS_MASTERDIR"
     readonly XBPS_RECONFIGURE_CMD="xbps-reconfigure -r $XBPS_MASTERDIR"
     readonly XBPS_REMOVE_CMD="xbps-remove -r $XBPS_MASTERDIR"
     readonly XBPS_SRCPKGDIR=$XBPS_DISTDIR/srcpkgs
     readonly XBPS_COMMONDIR=$XBPS_DISTDIR/common
-    readonly XBPS_SHUTILSDIR=$XBPS_COMMONDIR/xbps-src/shutils
     readonly XBPS_DESTDIR=$XBPS_MASTERDIR/destdir
     readonly XBPS_BUILDDIR=$XBPS_MASTERDIR/builddir
-    readonly XBPS_TRIGGERSDIR=$XBPS_SRCPKGDIR/xbps-triggers/files
-    readonly XBPS_CROSSPFDIR=$XBPS_COMMONDIR/cross-profiles
-    readonly XBPS_BUILDSTYLEDIR=$XBPS_COMMONDIR/build-style
-    readonly XBPS_LIBEXECDIR=$XBPS_COMMONDIR/xbps-src/libexec
-    readonly XBPS_BUILDHELPERDIR=$XBPS_COMMONDIR/build-helper
 fi
+readonly XBPS_RINDEX_CMD="xbps-rindex"
 readonly XBPS_FETCH_CMD="xbps-uhelper fetch"
 readonly XBPS_DIGEST_CMD="xbps-uhelper digest"
 readonly XBPS_CMPVER_CMD="xbps-uhelper cmpver"
+readonly XBPS_SHUTILSDIR=$XBPS_COMMONDIR/xbps-src/shutils
+readonly XBPS_TRIGGERSDIR=$XBPS_SRCPKGDIR/xbps-triggers/files
+readonly XBPS_CROSSPFDIR=$XBPS_COMMONDIR/cross-profiles
+readonly XBPS_BUILDSTYLEDIR=$XBPS_COMMONDIR/build-style
+readonly XBPS_LIBEXECDIR=$XBPS_COMMONDIR/xbps-src/libexec
+readonly XBPS_BUILDHELPERDIR=$XBPS_COMMONDIR/build-helper
 
+# command args
 readonly XBPS_TARGET="$1"
 if [ -n "$2" ]; then
     XBPS_TARGET_PKG="${2##*/}"
@@ -574,14 +578,11 @@ if [ -n "${NO_COLOR+x}" ]; then
     export NOCOLORS=1
 fi
 
-chroot_check() {
-    if [ -f $XBPS_MASTERDIR/.xbps_chroot_init -o "$XBPS_CHROOT_CMD" = "ethereal" ]; then
-        export CHROOT_READY=1
-    fi
-}
-
+# Check for CHROOT_READY and set up XBPS_ARCH environment var for xbps.
 chroot_check
+check_native_arch
 
+# Reconfigure pkgs for 32bit on x86_64 and reexec itself.
 if [ -z "$XBPS_REINIT" -a -s $XBPS_MASTERDIR/.xbps_chroot_init ]; then
     export XBPS_ARCH=${XBPS_ARCH:-$(cat $XBPS_MASTERDIR/.xbps_chroot_init)}
     if [[ $XBPS_MACHINE == x86_64* ]] && [[ $XBPS_ARCH == i686* ]]; then
@@ -592,19 +593,14 @@ if [ -z "$XBPS_REINIT" -a -s $XBPS_MASTERDIR/.xbps_chroot_init ]; then
         exec linux32 $0 ${XBPS_OPTIONS} $@
     fi
 fi
-if [ -n "$XBPS_ARCH" ]; then
-    export XBPS_MACHINE=$XBPS_ARCH
-fi
-if [ -z "$XBPS_TARGET_MACHINE" ]; then
-    export XBPS_TARGET_MACHINE=${XBPS_ARCH:=$XBPS_MACHINE}
-fi
 
+# Export relevant vars to the environment.
 export XBPS_SHUTILSDIR XBPS_CROSSPFDIR XBPS_TRIGGERSDIR \
-    XBPS_SRCPKGDIR XBPS_COMMONDIR XBPS_BUILDDIR XBPS_REPO_DELTAS \
+    XBPS_SRCPKGDIR XBPS_COMMONDIR XBPS_BUILDDIR \
     XBPS_REPOSITORY XBPS_ALT_REPOSITORY XBPS_SRCDISTDIR XBPS_DIGEST_CMD \
     XBPS_UHELPER_CMD XBPS_INSTALL_CMD XBPS_QUERY_CMD XBPS_BUILD_ONLY_ONE_PKG \
     XBPS_RINDEX_CMD XBPS_RECONFIGURE_CMD XBPS_REMOVE_CMD \
-    XBPS_CMPVER_CMD XBPS_FETCH_CMD XBPS_VERSION XBPS_APIVER XBPS_BUILDSTYLEDIR \
+    XBPS_CMPVER_CMD XBPS_FETCH_CMD XBPS_VERSION XBPS_BUILDSTYLEDIR \
     XBPS_CPPFLAGS XBPS_CFLAGS XBPS_CXXFLAGS XBPS_FFLAGS XBPS_LDFLAGS \
     XBPS_MAKEJOBS XBPS_BUILD_FORCEMODE XBPS_USE_GIT_REVS XBPS_DEBUG_PKGS \
     XBPS_CHECK_PKGS XBPS_CCACHE XBPS_DISTCC XBPS_DISTCC_HOSTS XBPS_SKIP_DEPS \
@@ -614,6 +610,7 @@ export XBPS_SHUTILSDIR XBPS_CROSSPFDIR XBPS_TRIGGERSDIR \
     XBPS_LIBEXECDIR XBPS_DISTDIR XBPS_DISTFILES_MIRROR XBPS_ALLOW_RESTRICTED \
     XBPS_USE_GIT_COMMIT_DATE XBPS_PKG_COMPTYPE XBPS_BUILDHELPERDIR
 
+# Create XBPS_{REPOSITORY,DESTDIR,BUILDDIR,SRCDISTDIR} dirs
 for i in REPOSITORY DESTDIR BUILDDIR SRCDISTDIR; do
     eval val="\$XBPS_$i"
     if [ ! -d "$val" ]; then
@@ -622,7 +619,7 @@ for i in REPOSITORY DESTDIR BUILDDIR SRCDISTDIR; do
     unset val
 done
 
-# A temporary masterdir requires xbps-uchroot(8) and -O to use overlayfs
+# A temporary masterdir requires xbps-uchroot(1) and -O to use overlayfs
 # on tmpfs (available with xbps-0.45).
 if [ -z "$IN_CHROOT" -a -n "$XBPS_TEMP_MASTERDIR" ]; then
     export XBPS_CHROOT_CMD="uchroot"
@@ -671,6 +668,12 @@ fi
 
 reconfigure_bootstrap_pkgs
 
+# At this point if XBPS_TARGET_MACHINE isn't defined we assume
+# it's a native build.
+if [ -z "$XBPS_TARGET_MACHINE" ]; then
+    export XBPS_TARGET_MACHINE=$XBPS_MACHINE
+fi
+
 #
 # Main switch.
 #
@@ -680,7 +683,6 @@ case "$XBPS_TARGET" in
         ;;
     bootstrap)
         # bootstrap from sources
-        # check for required host utils
         check_reqhost_utils bootstrap
         [ ! -d $XBPS_SRCPKGDIR/base-chroot ] && \
             msg_error "Cannot find $XBPS_SRCPKGDIR/base-chroot directory!\n"
@@ -688,12 +690,12 @@ case "$XBPS_TARGET" in
         mkdir -p ${XBPS_MASTERDIR}/etc/xbps.d
         if [ ! -s ${bootstrap_vpkg} ]; then
             # Fool xbps to resolve dependencies.
-            echo 'virtualpkg=libgcc-4.4.0_1:base-files' >> ${bootstrap_vpkg}
-            echo 'virtualpkg=libstdc++-4.4.0_1:base-files' >> ${bootstrap_vpkg}
+            echo 'virtualpkg=libgcc:base-files' >> ${bootstrap_vpkg}
+            echo 'virtualpkg=libstdc++:base-files' >> ${bootstrap_vpkg}
         fi
         $XBPS_LIBEXECDIR/build.sh base-chroot base-chroot $XBPS_TARGET || exit 1
         [ -d $XBPS_MASTERDIR ] && rm -rf $XBPS_MASTERDIR
-        install_bbootstrap bootstrap
+        install_bbootstrap
         ;;
     bootstrap-update)
         bootstrap_update
