Revert "xbps-src: fix uchroot chroot-style to not overwrite XBPS_CHROOT_CMD_ARGS."
This reverts commit ba4bba203118a1b90bb239eeedbaf89a7fed8c0f.

diff --git a/xbps-src b/xbps-src
--- a/xbps-src
+++ b/xbps-src
@@ -570,6 +570,15 @@ for i in REPOSITORY DESTDIR BUILDDIR SRCDISTDIR; do
     unset val
 done
 
+# A temporary masterdir requires xbps-uchroot(8) and -O to use overlayfs
+# on tmpfs (available with xbps-0.45).
+if [ -z "$IN_CHROOT" -a -n "$XBPS_TEMP_MASTERDIR" ]; then
+    if [ "$XBPS_CHROOT_CMD" != "uchroot" ]; then
+        echo "ERROR: -t requires XBPS_CHROOT_CMD=uchroot, exiting..."
+        exit 1
+    fi
+    export XBPS_CHROOT_CMD_ARGS="-O"
+fi
 #
 # Sanitize PATH.
 #
