gnome-desktop: add do_check

diff --git a/srcpkgs/gnome-desktop/template b/srcpkgs/gnome-desktop/template
--- a/srcpkgs/gnome-desktop/template
+++ b/srcpkgs/gnome-desktop/template
@@ -11,6 +11,7 @@ makedepends="eudev-libudev-devel gsettings-desktop-schemas-devel gtk+3-devel
  iso-codes libglib-devel libseccomp-devel libX11-devel libXext-devel
  libxkbfile-devel libXrandr-devel gdk-pixbuf-devel"
 depends="bubblewrap gsettings-desktop-schemas iso-codes xkeyboard-config"
+checkdepends="$depends xorg-server-xvfb"
 short_desc="GNOME desktop management utilities"
 maintainer="Enno Boland <gottox@voidlinux.org>"
 license="GPL-2.0-or-later, LGPL-2.1-or-later"
@@ -20,6 +21,22 @@ checksum=38f994dcb1e1ae093d1c929c7acc4f88e39111e43b5fdc13125b0f6e2311c789
 
 build_options="gir"
 build_options_default="gir"
+
+do_check() {
+	# there is still 1 test fail for he_IL locale in musl
+	if test "$XBPS_TARGET_LIBC" != musl; then
+		local _pid
+		Xvfb :1 -screen 0 1366x768x24 &
+		_pid=$!
+		trap "kill $_pid" EXIT
+		trap 'exit 1' INT HUP TERM
+		export DISPLAY=:1
+		ninja -C build test
+		trap - EXIT INT HUP TERM
+		kill $_pid
+	fi
+}
+
 
 gnome-desktop-devel_package() {
 	depends="gtk+3-devel gsettings-desktop-schemas-devel>=3.12
