xbps-src: show all missing required host utilities, add gzip/bzip2.

diff --git a/xbps-src/xbps-src.sh.in b/xbps-src/xbps-src.sh.in
--- a/xbps-src/xbps-src.sh.in
+++ b/xbps-src/xbps-src.sh.in
@@ -34,19 +34,24 @@
 : ${xbps_machine:=$(uname -m)}
 
 # Required utilities in host system.
-REQHOST_UTILS="gawk bash bison sed gcc msgfmt patch makeinfo perl fakeroot tar xz"
+REQHOST_UTILS="awk bash bison sed gcc msgfmt patch makeinfo \
+	perl fakeroot tar xz gzip bzip2"
 
 check_reqhost_utils()
 {
+	local broken
+
 	[ -n "$IN_CHROOT" ] && return 0
 	[ -r "$XBPS_MASTERDIR/.xbps_perms_done" ] && return 0
 
 	for f in ${REQHOST_UTILS}; do
 		if ! command -v ${f} 2>&1 >/dev/null; then
-			echo "${f} is missing in your system, can't continue! exiting..."
-			exit 1
+			echo "${f} is missing in your system, can't continue!"
+			broken=1
 		fi
 	done
+
+	[ -n "$broken" ] && exit 1
 }
 
 usage()
