Added support for extended pkgdep version matching.
xbps from launchpad head branch has gained support for extended
pkg version matching, as specified in:

https://blueprints.launchpad.net/xbps/+spec/improved-version-matching

Now it's required to specify the operator(s) for required versions
in the depends files and "Add_dependency" option in build templates.

xbps-src now requires xbps utils 20091107.

--HG--
extra : convert_revision : fc09fa707483a75e0b6f68445721fc1a9166cdad

diff --git a/xbps-src/xbps-src.sh.in b/xbps-src/xbps-src.sh.in
--- a/xbps-src/xbps-src.sh.in
+++ b/xbps-src/xbps-src.sh.in
@@ -30,6 +30,7 @@ trap "echo && exit 1" INT QUIT
 : ${progname:=$(basename $0)}
 : ${fakeroot_cmd:=fakeroot}
 : ${xbps_machine:=$(uname -m)}
+: ${XBPS_UTILS_REQVER:=20091107}
 
 usage()
 {
@@ -89,7 +90,7 @@ run_file()
 
 set_defvars()
 {
-	local DDIRS i
+	local DDIRS i instver
 
 	: ${XBPS_TEMPLATESDIR:=$XBPS_DISTRIBUTIONDIR/templates}
 	: ${XBPS_TRIGGERSDIR:=$XBPS_DISTRIBUTIONDIR/triggers}
@@ -112,6 +113,18 @@ set_defvars()
 	export XBPS_DIGEST_CMD="xbps-digest.static"
 	export XBPS_CMPVER_CMD="xbps-cmpver.static"
 	export XBPS_FETCH_CMD="xbps-fetch.static"
+
+	#
+	# Check that installed xbps utils version is recent enough.
+	#
+	instver=$(${XBPS_PKGDB_CMD} -V)
+	${XBPS_CMPVER_CMD} "${instver}" "${XBPS_UTILS_REQVER}"
+	if [ $? -eq 255 ]; then
+		echo -n "Your xbps utilities are too old, "
+		echo "required version: ${XBPS_UTILS_REQVER}"
+		exit 1
+	fi
+
 }
 
 #
