xbps-src: always try to unmount via xbps-src-chroot-helper before exiting.

diff --git a/xbps-src/xbps-src.sh.in b/xbps-src/xbps-src.sh.in
--- a/xbps-src/xbps-src.sh.in
+++ b/xbps-src/xbps-src.sh.in
@@ -23,8 +23,6 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #-
-trap "echo && exit 1" INT QUIT
-
 : ${XBPS_CONFIG_FILE:=@@XBPS_INSTALL_ETCDIR@@/xbps-src.conf}
 
 : ${progname:=$(basename $0)}
@@ -34,6 +32,18 @@ trap "echo && exit 1" INT QUIT
 : ${chroot_cmd:=chroot}
 : ${xbps_machine:=$(uname -m)}
 : ${XBPS_UTILS_REQVER:=20100511}
+
+trap 'sighandler_exit $?' 0 INT QUIT
+
+sighandler_exit()
+{
+	# Always unmount in case, we failed before!
+	if [ -z "$in_chroot" ]; then
+        	@@XBPS_INSTALL_LIBEXECDIR@@/xbps-src-chroot-helper umount
+	fi
+	[ -n "$1" ] && exit $1
+	exit $?
+}
 
 usage()
 {
