libxslt: fix manpage + remove second distfile

diff --git a/srcpkgs/libxslt/template b/srcpkgs/libxslt/template
--- a/srcpkgs/libxslt/template
+++ b/srcpkgs/libxslt/template
@@ -1,19 +1,17 @@
 # Template file for 'libxslt'
 pkgname=libxslt
 version=1.1.34
-revision=4
+revision=5
 build_style=gnu-configure
 configure_args="--disable-static --disable-dependency-tracking"
-hostmakedepends="libtool python-devel libxml2-python pkg-config"
+hostmakedepends="docbook-xml docbook-xsl libtool python-devel libxml2-python pkg-config"
 makedepends="python-devel libxml2-devel libxml2-python libgcrypt-devel"
 short_desc="XSLT parser library from the GNOME project"
 maintainer="Orphaned <orphan@voidlinux.org>"
 license="MIT"
 homepage="http://xmlsoft.org/XSLT/"
-distfiles="http://xmlsoft.org/sources/libxslt-${version}.tar.gz
-	ftp://xmlsoft.org/${pkgname}/${pkgname}-${version}.tar.gz"
-checksum="98b1bd46d6792925ad2dfe9a87452ea2adebf69dcb9919ffd55bf926a7f93f7f
- 98b1bd46d6792925ad2dfe9a87452ea2adebf69dcb9919ffd55bf926a7f93f7f"
+distfiles="http://xmlsoft.org/sources/libxslt-${version}.tar.gz"
+checksum="98b1bd46d6792925ad2dfe9a87452ea2adebf69dcb9919ffd55bf926a7f93f7f"
 
 post_configure() {
 	# Remove missing seperators and errors
@@ -28,6 +26,19 @@ post_configure() {
 	fi
 }
 
+post_build() {
+	if [ ! "$CROSS_BUILD" ]; then
+		# xsltproc manpage depends on xsltproc, this remakes it after
+		# libxslt is build
+		# this doesn't work when cross compiling
+		make -C doc XSLTPROC=${wrksrc}/xsltproc/xsltproc xsltproc.1
+		if ! cmp --silent ${wrksrc}/doc/xsltproc.1 ${FILESDIR}/xsltproc.1; then
+			echo "WARNING: Backup manpage is outdated!"
+			[ ! "$XBPS_CHECK_PKGS" ] # make build fail when checking
+		fi
+	fi
+}
+
 post_install() {
 	if [ "$CROSS_BUILD" ]; then
 		# Remove $XBPS_CROSS_BASE in pkg-config
@@ -35,6 +46,9 @@ post_install() {
 			$DESTDIR/usr/bin/xslt-config
 		vsed -i -e "s,$XBPS_CROSS_BASE,,g" \
 			$DESTDIR/usr/lib/pkgconfig/libexslt.pc
+
+		# use the backup manpage when it can't be built normally
+		vman ${FILESDIR}/xsltproc.1
 	fi
 	vlicense COPYING
 }
