xbps-src: make -B flag build binpkgs for required pkg deps.

diff --git a/xbps-src/libexec/chroot-helper.sh.in b/xbps-src/libexec/chroot-helper.sh.in
--- a/xbps-src/libexec/chroot-helper.sh.in
+++ b/xbps-src/libexec/chroot-helper.sh.in
@@ -26,16 +26,6 @@
 
 HANDLER="$1"
 
-. @@XBPS_INSTALL_ETCDIR@@/xbps-src.conf
-
-if [ -n "${MASTERDIR}" ]; then
-	export XBPS_MASTERDIR="${MASTERDIR}"
-fi
-if [ -n "${HOSTDIR}" ]; then
-	export XBPS_HOSTDIR="${HOSTDIR}"
-fi
-
-
 REQFS="sys proc dev xbps host"
 
 mount_chroot_fs()
@@ -43,42 +33,42 @@ mount_chroot_fs()
 	local cnt f blah dowrite
 
 	for f in ${REQFS}; do
-		if [ ! -f ${XBPS_MASTERDIR}/.${f}_mount_bind_done ]; then
+		if [ ! -f ${MASTERDIR}/.${f}_mount_bind_done ]; then
 			unset dowrite
 			echo -n "=> Mounting /${f} in chroot... "
-			if [ ! -d ${XBPS_MASTERDIR}/${f} ]; then
-				mkdir -p ${XBPS_MASTERDIR}/${f}
+			if [ ! -d ${MASTERDIR}/${f} ]; then
+				mkdir -p ${MASTERDIR}/${f}
 			fi
 			case ${f} in
 				xbps)
-					blah=${XBPS_DISTRIBUTIONDIR}
+					blah=${DISTRIBUTIONDIR}
 					dowrite="-w"
 					;;
 				host)
-					blah=${XBPS_HOSTDIR}
+					blah=${HOSTDIR}
 					dowrite="-w"
 					;;
 				*) blah=/${f};;
 			esac
-			if [ -z "$XBPS_HOSTDIR" -a "$f" = "host" ]; then
+			if [ -z "$HOSTDIR" -a "$f" = "host" ]; then
 				echo "unset, ignoring."
 				continue
 			fi
 			[ ! -d ${blah} ] && echo "failed." && continue
 			@@XBPS_INSTALL_LIBEXECDIR@@/capmount \
-				${dowrite} ${blah} ${XBPS_MASTERDIR}/${f} \
+				${dowrite} ${blah} ${MASTERDIR}/${f} \
 				2>/dev/null
 			if [ $? -eq 0 ]; then
-				echo 1 > ${XBPS_MASTERDIR}/.${f}_mount_bind_done
+				echo 1 > ${MASTERDIR}/.${f}_mount_bind_done
 				echo "done."
 			else
 				echo "FAILED!"
 				exit 1
 			fi
 		else
-			cnt=$(cat ${XBPS_MASTERDIR}/.${f}_mount_bind_done)
+			cnt=$(cat ${MASTERDIR}/.${f}_mount_bind_done)
 			cnt=$((${cnt} + 1))
-			echo ${cnt} > ${XBPS_MASTERDIR}/.${f}_mount_bind_done
+			echo ${cnt} > ${MASTERDIR}/.${f}_mount_bind_done
 		fi
 	done
 }
@@ -88,17 +78,17 @@ umount_chroot_fs()
 	local fs dir cnt
 
 	for fs in ${REQFS}; do
-		[ ! -f ${XBPS_MASTERDIR}/.${fs}_mount_bind_done ] && continue
-		cnt=$(cat ${XBPS_MASTERDIR}/.${fs}_mount_bind_done)
+		[ ! -f ${MASTERDIR}/.${fs}_mount_bind_done ] && continue
+		cnt=$(cat ${MASTERDIR}/.${fs}_mount_bind_done)
 		if [ ${cnt} -gt 1 ]; then
 			cnt=$((${cnt} - 1))
-			echo ${cnt} > ${XBPS_MASTERDIR}/.${fs}_mount_bind_done
+			echo ${cnt} > ${MASTERDIR}/.${fs}_mount_bind_done
 		else
 			echo -n "=> Unmounting ${fs} from chroot... "
 			@@XBPS_INSTALL_LIBEXECDIR@@/capumount \
-				${XBPS_MASTERDIR} ${fs} 2>/dev/null
+				${MASTERDIR} ${fs} 2>/dev/null
 			if [ $? -eq 0 ]; then
-				rm -f ${XBPS_MASTERDIR}/.${fs}_mount_bind_done
+				rm -f ${MASTERDIR}/.${fs}_mount_bind_done
 				echo "done."
 			else
 				echo "FAILED!!!"
@@ -110,6 +100,11 @@ umount_chroot_fs()
 
 if [ $# -ne 1 ]; then
 	echo "$0: mount || umount"
+	exit 1
+fi
+
+if [ -z "$MASTERDIR" -o -z "$DISTRIBUTIONDIR" ]; then
+	echo "$0: MASTERDIR or DISTRIBUTIONDIR unset, can't continue."
 	exit 1
 fi
 
