xbps-src: do not umount if <masterdir>/.xbps_chroot_working is there.

diff --git a/xbps-src/libexec/xbps-src-chroot-helper.sh.in b/xbps-src/libexec/xbps-src-chroot-helper.sh.in
--- a/xbps-src/libexec/xbps-src-chroot-helper.sh.in
+++ b/xbps-src/libexec/xbps-src-chroot-helper.sh.in
@@ -60,7 +60,8 @@ mount_chroot_fs()
 				echo 1 > ${XBPS_MASTERDIR}/.${f}_mount_bind_done
 				echo "done."
 			else
-				echo "failed."
+				echo "FAILED!!!!!"
+				exit 1
 			fi
 		else
 			cnt=$(cat ${XBPS_MASTERDIR}/.${f}_mount_bind_done)
@@ -73,6 +74,10 @@ mount_chroot_fs()
 umount_chroot_fs()
 {
 	local fs dir cnt
+
+	if [ -f ${XBPS_MASTERDIR}/.xbps_chroot_working ]; then
+		return 0
+	fi
 
 	for fs in ${REQFS}; do
 		[ ! -f ${XBPS_MASTERDIR}/.${fs}_mount_bind_done ] && continue
@@ -88,7 +93,7 @@ umount_chroot_fs()
 				rm -f ${XBPS_MASTERDIR}/.${fs}_mount_bind_done
 				echo "done."
 			else
-				echo "failed."
+				echo "FAILED!!!"
 			fi
 		fi
 		unset fs
