evolution-data-server: split vala build option from gir

diff --git a/srcpkgs/evolution-data-server/template b/srcpkgs/evolution-data-server/template
--- a/srcpkgs/evolution-data-server/template
+++ b/srcpkgs/evolution-data-server/template
@@ -2,45 +2,41 @@
 pkgname=evolution-data-server
 version=3.36.3
 revision=1
+_basever=${version%.*}
 build_style=cmake
 build_helper=gir
 configure_args="-DENABLE_UOA=OFF
- $(vopt_if gir '-DENABLE_INTROSPECTION=ON -DENABLE_VALA_BINDINGS=ON' '-DENABLE_WEATHER=OFF')"
+ $(vopt_if gir -DENABLE_INTROSPECTION=ON)
+ $(vopt_if vala -DENABLE_VALA_BINDINGS=ON)"
 hostmakedepends="flex glib-devel gperf intltool pkg-config libglib-devel
- $(vopt_if gir 'gobject-introspection')"
-makedepends="boost-devel libcanberra-devel libgdata-devel $(vopt_if gir libgweather-devel)
- libical-devel libsecret-devel mit-krb5-devel $(vopt_if gir 'vala-devel') webkit2gtk-devel"
-depends="$(vopt_if gir libgweather) libsoup-gnome"
+ $(vopt_if vala vala)"
+makedepends="boost-devel libcanberra-devel libgdata-devel libical-devel
+ libsecret-devel mit-krb5-devel webkit2gtk-devel libgweather-devel
+ $(vopt_if vala vala-devel)"
+depends="libgweather libsoup-gnome dbus tzdata"
+checkdepends="$depends"
 short_desc="Centralized access to appointments and contacts"
 maintainer="Enno Boland <gottox@voidlinux.org>"
 license="LGPL-2.1-only"
 homepage="https://wiki.gnome.org/Apps/Evolution"
-changelog="https://raw.githubusercontent.com/GNOME/evolution-data-server/gnome-3-36/NEWS"
-distfiles="${GNOME_SITE}/${pkgname}/${version%.*}/${pkgname}-${version}.tar.xz"
+changelog="https://raw.githubusercontent.com/GNOME/$pkgname/gnome-${_basever/./-}/NEWS"
+distfiles="${GNOME_SITE}/${pkgname}/${_basever}/${pkgname}-${version}.tar.xz"
 checksum=1f5f48173d0f288219d73d4f193cb921ae631932ba84030f05751c42bb003db2
 
-build_options="gir"
+build_options="gir vala"
 if [ -z "$CROSS_BUILD" ]; then
-	build_options_default="gir"
+	build_options_default="gir vala"
 fi
 
-# cmake perfomrms 2 checks using binary runtime, about iconv and sfrtime.
-# musl (1.1.16) does not support "ISO-2022-JP" encoding (see its roadmap),
-# although evolution-data-server is fine with musl.
-# If crossbuild, cmake let disabling runtime checks via specific directives.
-# test iconv-detect.c also generates iconv-detect.h that is required for build.
-# So completly disable test from iconv-detect.c (cmake.patch file) and
-# use a cmake cache file on crossbuild to disable sfrtime running test.
-if [ "$CROSS_BUILD" ]; then
-	configure_args+=" -C disableRuntimeTests.cmake"
-fi
 
-pre_configure() {
-	mkdir -p build
-	cp ${FILESDIR}/iconv-detect.h ${wrksrc}/build/.
-	if [ "$CROSS_BUILD" ]; then
-		cp ${FILESDIR}/disableRuntimeTests.cmake ${wrksrc}/build/.
-	fi
+do_check() {
+	cd build
+	# TODO This test is problematic, first run usually fail
+	# Signify something wrong with evolution-data-server on first run
+	ctest -R test-book-client-custom-summary || true
+	# make test run ctest --force-new-ctest-process which is problematic
+	# noone should run multiple instance of evolution-data-server irl.
+	ctest
 }
 
 post_install() {
@@ -59,6 +55,8 @@ evolution-data-server-devel_package() {
 		vmove "usr/lib/*.so"
 		if [ "$build_option_gir" ]; then
 			vmove usr/share/gir-1.0
+		fi
+		if [ "$build_option_vala" ]; then
 			vmove usr/share/vala
 		fi
 	}
