rpmextract: update to 1.2.

diff --git a/srcpkgs/rpmextract/files/rpmextract b/srcpkgs/rpmextract/files/rpmextract
--- a/srcpkgs/rpmextract/files/rpmextract
+++ b/srcpkgs/rpmextract/files/rpmextract
@@ -1,6 +1,10 @@
 #!/bin/sh
-if [ "$1" = "" -o ! -e "$1" ]; then
-    echo "no package supplied" 1>&2
-   exit 1
+
+if [ -z "$1" ]; then
+	echo "no package supplied" >&2
+	exit 1
+elif [ ! -f "$1" ]; then
+	echo "'$1': not found" >&2
+	exit 1
 fi
-rpm2cpio $1 | bsdtar -xf -
+rpm2cpio "$1" | bsdtar -xf -
