boswars: fix broken png + missing files
Closes: #5153 [via git-merge-pr]

diff --git a/srcpkgs/boswars/template b/srcpkgs/boswars/template
--- a/srcpkgs/boswars/template
+++ b/srcpkgs/boswars/template
@@ -1,9 +1,9 @@
 # Template file for 'boswars'
 pkgname=boswars
 version=2.7
-revision=3
+revision=4
 wrksrc="${pkgname}-${version}-src"
-hostmakedepends="pkg-config"
+hostmakedepends="pkg-config libpng-progs"
 makedepends="lua51-devel libtheora-devel libogg-devel libpng-devel libvorbis-devel MesaLib-devel SDL-devel"
 short_desc="A futuristic real-time strategy game (RTS)"
 maintainer="Diogo Leal <diogo@diogoleal.com>"
@@ -26,14 +26,28 @@ do_install() {
 	vmkdir usr/share/boswars
 	vcopy fbuild/release/boswars usr/share/boswars/
 	vcopy campaigns usr/share/boswars/
-	vcopy engine  usr/share/boswars/
+	vcopy doc usr/share/boswars/
 	vcopy graphics usr/share/boswars/
 	vcopy intro usr/share/boswars/
 	vcopy languages usr/share/boswars/
 	vcopy maps usr/share/boswars/
+	vcopy patches usr/share/boswars/
 	vcopy scripts usr/share/boswars/
 	vcopy sounds usr/share/boswars/
+	vcopy units usr/share/boswars/
 	vbin ${FILESDIR}/boswars
 	vinstall ${FILESDIR}/boswars.desktop 644 usr/share/applications/
 	vinstall ${FILESDIR}/boswars.png 644 usr/share/pixmaps/
+}
+
+post_extract() {
+	#png bugfix for version 2.7, https://savannah.nongnu.org/bugs/?39610
+
+	for i in $(find . -iname '*.png'); do
+		pngfix -q ${i} || {
+			echo "Fixing ${i}"
+			pngfix -q --out=${i/.png/_fixed.png} ${i} || : #ignore exit code
+			pngfix -q ${i/.png/_fixed.png} && mv ${i/.png/_fixed.png} ${i};
+		}
+	done
 }
