initramfs-tools: sync code with upstream 0.98.5.

diff --git a/srcpkgs/initramfs-tools/files/hook-functions b/srcpkgs/initramfs-tools/files/hook-functions
--- a/srcpkgs/initramfs-tools/files/hook-functions
+++ b/srcpkgs/initramfs-tools/files/hook-functions
@@ -3,7 +3,7 @@
 catenate_cpiogz() {
 	# Sanity check
 	if [ ! -e "${1}" ]; then
-		echo "W:catenate_cpiogz: arg1='${1}' does not exist." >&2
+		echo "W: catenate_cpiogz: arg1='${1}' does not exist." >&2
 		return
 	fi
 
@@ -29,7 +29,7 @@ add_modules_from_file()
 {
 	# Sanity check
 	if [ ! -e "${1}" ]; then
-		echo "W:add_modules_from_file: arg1='${1}' does not exist." >&2
+		echo "W: add_modules_from_file: arg1='${1}' does not exist." >&2
 		return
 	fi
 
@@ -73,6 +73,7 @@ manual_add_modules()
 				if [ ! -e /proc/modules ] ; then
 					continue
 				fi
+
 				if grep -q "^$(basename "${kmod}" .ko)[[:space:]]" \
 				/proc/modules \
 				|| grep -q "^$(basename "${kmod}" .ko)" \
@@ -113,7 +114,7 @@ copy_exec() {
 	[ -f "${src}" ] || return 1
 
 	if [ -d "${DESTDIR}/${target}" ]; then
-               # check if already copied
+		# check if already copied
 		[ -e "${DESTDIR}/$target/${src##*/}" ] && return 0
 	else
 		[ -e "${DESTDIR}/$target" ] && return 0
@@ -126,10 +127,10 @@ copy_exec() {
 
 	# Copy the dependant libraries
 	for x in $(ldd ${src} 2>/dev/null | sed -e '
-	    /\//!d;
-	    /linux-gate/d;
-	    /=>/ {s/.*=>[[:blank:]]*\([^[:blank:]]*\).*/\1/};
-	    s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
+		/\//!d;
+		/linux-gate/d;
+		/=>/ {s/.*=>[[:blank:]]*\([^[:blank:]]*\).*/\1/};
+		s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
 
 		# Try to use non-optimised libraries where possible.
 		# We assume that all HWCAP libraries will be in tls,
@@ -147,7 +148,7 @@ copy_exec() {
 		mkdir -p "${DESTDIR}/${dirname}"
 		if [ ! -e "${DESTDIR}/${dirname}/${libname}" ]; then
 			ln -s "${x}" "${DESTDIR}/${dirname}"
-			[ "${verbose}" = "y" ] && echo "Adding library ${x}"
+			[ "${verbose}" = "y" ] && echo "Adding library ${x}" || true
 		fi
 	done
 }
@@ -165,7 +166,7 @@ copy_modules_dir()
 	if [ "${verbose}" = "y" ]; then
 		echo "Copying module directory ${dir}"
 		if [ $# -ge 1 ]; then
-		  echo "(excluding $*)"
+			echo "(excluding $*)"
 		fi
 	fi
 	while [ $# -ge 1 ]; do
@@ -182,7 +183,7 @@ sys_walk_mod_add()
 {
 	local driver_path module
 	device_path="$1"
-	
+
 	while [ "${device_path}" != "/sys" ]; do
 		sys_walk_modalias ${device_path}
 		driver_path="$(readlink -f ${device_path}/driver/module)"
@@ -219,12 +220,38 @@ dep_add_modules()
 
 	# require mounted sysfs
 	if [ ! -d /sys/devices/ ]; then
-		echo "mkinitramfs: MODULES dep requires mounted sysfs on /sys"
+		echo "mkinitramfs: MODULES dep requires mounted sysfs on /sys" >&2
 		exit 1
 	fi
 
 	# findout root block device + fstype
 	eval "$(mount | awk '/\/dev\// {if ($3 == "/") {print "root=" $1 "\nFSTYPE=" $5; exit}}')"
+
+	# On failure fallback to /proc/mounts if readable
+	if [ -z "$root" ] && [ -r /proc/mounts ]; then
+		eval "$(awk '/\/dev\// {if ($2 == "/") {print "root=" $1 "\nFSTYPE=" $5; exit}}' /proc/mounts)"
+	fi
+
+	# recheck root device
+	if [ -z "$root" ]; then
+		echo "mkinitramfs: failed to determine root device" >&2
+		echo "mkinitramfs: workaround is MODULES=most" >&2
+		echo "Error please report bug on initramfs-tools" >&2
+		echo "Include the output of 'mount' and 'cat /proc/mounts'" >&2
+		exit 1
+	fi
+
+	# handle ubifs and return since ubifs root is a char device but
+	# most of the commands below only work with block devices.
+	if [ "${FSTYPE}" = "ubifs" ]; then
+		manual_add_modules "${FSTYPE}"
+		# add some modules required by ubifs on which it doesn's depend
+		manual_add_modules deflate
+		manual_add_modules zlib
+		manual_add_modules lzo
+		return
+	fi
+
 	if [ "${root}" = "/dev/root" ] ; then
 		root="/dev/disk/by-uuid/"$(blkid -o value -s UUID ${root}) 2>/dev/null
 	fi
@@ -239,10 +266,10 @@ dep_add_modules()
 	if [ "${FSTYPE}" = "unknown" ]; then
 		FSTYPE=$(blkid -o value -s TYPE "${root}")
 		if [  -z "${FSTYPE}" ]; then
-			echo "mkinitramfs: unknown fstype on root ${root}"
-			echo "mkinitramfs: workaround is MODULES=most" 
-			echo "Error please report bug on initramfs-tools"
-		exit 1
+			echo "mkinitramfs: unknown fstype on root ${root}" >&2
+			echo "mkinitramfs: workaround is MODULES=most" >&2
+			echo "Error please report bug on initramfs-tools" >&2
+			exit 1
 		fi
 	fi
 
@@ -260,8 +287,7 @@ dep_add_modules()
 		done
 		# lvm on md or luks on md
 		if [ "${block#md}" != "${block}" ]; then
-			block=$(awk "/^${block}/{print substr(\$5, 1, 4); exit}" \
-				/proc/mdstat)
+			block=$(sed -ne 's/multipath/[/' -e 's/linear/[/' -e 's/raid[0-9][0-9]*/[/' -e 's/\([hs]d[a-z][a-z]*\)[0-9][0-9]*/\1/g' -e '/^'${block}' :/s/^[^[]*\[ \([^\[]*\)\[.*$/\1/p' </proc/mdstat)
 		fi
 		# luks or lvm on cciss or ida
 		if [ "${block#cciss}" != "${block}" ] \
@@ -273,13 +299,15 @@ dep_add_modules()
 	# md root new naming scheme /dev/md/X
 	elif [ "${root#/dev/md/}" != "${root}" ]; then
 		root=${root#/dev/md/}
-		block=$(awk "/^md${root}/{print substr(\$5, 1, 3); exit}" \
-			/proc/mdstat)
+		# drop the partition number only for sdX and hdX devices
+		# and keep it for other devices like loop#, dm-# devices
+		block=$(sed -ne 's/multipath/[/' -e 's/linear/[/' -e 's/raid[0-9][0-9]*/[/' -e 's/\([hs]d[a-z][a-z]*\)[0-9][0-9]*/\1/g' -e '/^md'$root' :/s/^[^[]*\[ \([^\[]*\)\[.*$/\1/p' </proc/mdstat)
 	# md root /dev/mdX
 	elif [ "${root#/dev/md}" != "${root}" ]; then
-		root=${root#/dev/}
-		block=$(awk "/^${root}/{print substr(\$5, 1, 3); exit}" \
-			/proc/mdstat)
+		root=${root#/dev/md}
+		# drop the partition number only for sdX and hdX devices
+		# and keep it for other devices like loop#, dm-# devices
+		block=$(sed -ne 's/multipath/[/' -e 's/linear/[/' -e 's/raid[0-9][0-9]*/[/' -e 's/\([hs]d[a-z][a-z]*\)[0-9][0-9]*/\1/g' -e '/^md'$root' :/s/^[^[]*\[ \([^\[]*\)\[.*$/\1/p' </proc/mdstat)
 	# cciss device
 	elif [ "${root#/dev/cciss/}" != "${root}" ]; then
 		block=${root#/dev/cciss/*}
@@ -320,9 +348,9 @@ dep_add_modules()
 
 	# Error out if /sys lack block dev
 	if [ -z "${block}" ] || [ ! -e /sys/block/${block} ]; then
-		echo "mkinitramfs: for root ${root} missing ${block} /sys/block/ entry"
-		echo "mkinitramfs: workaround is MODULES=most" 
-		echo "mkinitramfs: Error please report the bug" 
+		echo "mkinitramfs: for root ${root} missing ${block} /sys/block/ entry" >&2
+		echo "mkinitramfs: workaround is MODULES=most" >&2
+		echo "mkinitramfs: Error please report the bug" >&2
 		exit 1
 	fi
 
@@ -345,6 +373,10 @@ dep_add_modules()
 
 	if [ -e /sys/bus/mmc/devices/ ]; then
 		manual_add_modules mmc_block
+	fi
+
+	if [ -e /sys/bus/virtio ] ; then
+		manual_add_modules virtio_pci
 	fi
 
 	if [ -e /sys/bus/i2o/devices/ ]; then
@@ -372,7 +404,7 @@ auto_add_modules()
 	case "${1:-}" in
 	base)
 		for x in ehci-hcd ohci-hcd uhci-hcd usbhid xhci hid-apple \
-		hid-microsoft \
+		hid-cherry hid-logitech hid-microsoft \
 		btrfs ext2 ext3 ext4 ext4dev isofs jfs nfs reiserfs udf xfs \
 		af_packet atkbd i8042 virtio_pci; do
 			manual_add_modules "${x}"
@@ -405,6 +437,11 @@ auto_add_modules()
 	;;
 	block)
 		copy_modules_dir kernel/drivers/block
+	;;
+	ubi)
+		for x in deflate zlib lzo ubi ubifs; do
+			manual_add_modules "${x}"
+		done
 	;;
 	ieee1394)
 		for x in ohci1394 sbp2; do
@@ -455,11 +492,11 @@ usage()
 Usage: ${0} [OPTION]... -o outfile [version]
 
 Options:
-  -c compress  Override COMPRESS setting in initramfs.conf.
-  -d confdir   Specify an alternative configuration directory.
-  -k           Keep temporary directory used to make the image.
-  -o outfile   Write to outfile.
-  -r root      Override ROOT setting in initramfs.conf.
+  -c compress	Override COMPRESS setting in initramfs.conf.
+  -d confdir	Specify an alternative configuration directory.
+  -k		Keep temporary directory used to make the image.
+  -o outfile	Write to outfile.
+  -r root	Override ROOT setting in initramfs.conf.
 
 See mkinitramfs(8) for further details.
 EOF
@@ -490,9 +527,9 @@ compare_versions()
 	xbps-uhelper cmpver $curv $minv
 	if [ $? -eq 0 ] || [ $? -eq 1 ]; then
 		return 0
-	else
-		return 1
 	fi
+
+	return 1
 }
 
 # minimal supported kernel version
@@ -503,8 +540,7 @@ check_minkver()
 	curversion="${1:-}"
 	initdir="${2:-}"
 	if [ -z "${initdir}" ]; then
-		ARCH=$(uname -m)
-		case ${ARCH} in
+		case ${ARCH:-} in
 			ia64|hppa)
 				minversion="2.6.15"
 			;;
@@ -521,10 +557,10 @@ check_minkver()
 	fi
 	set_initlist
 	for cm_x in ${initlist:-}; do
-		# sed: keep last line starting with MINKVER=,
-		#      remove MINKVER= and trailing space
+		# sed:  keep last line starting with MINKVER=,
+		#	remove MINKVER= and trailing space
 		minver=$(sed '/^MINKVER=/!d;$!d;s/^MINKVER=//;s/[[:space:]]*$//' "${initdir}/${cm_x}")
-		if [ -z "${tmp}" ]; then
+		if [ -z "${tmp:-}" ]; then
 			continue
 		elif ! compare_versions "${curversion}" "${minver}"; then
 			echo "W: ${cm_x} hook script requires at least kernel version ${minver}" >&2
diff --git a/srcpkgs/initramfs-tools/files/mkinitramfs b/srcpkgs/initramfs-tools/files/mkinitramfs
--- a/srcpkgs/initramfs-tools/files/mkinitramfs
+++ b/srcpkgs/initramfs-tools/files/mkinitramfs
@@ -7,12 +7,11 @@ export PATH='/usr/bin:/sbin:/bin'
 keep="n"
 CONFDIR="/etc/initramfs-tools"
 verbose="n"
-errors_to="2>/dev/null"
 
 OPTIONS=`getopt -o c:d:ko:r:v -n "$0" -- "$@"`
 
 # Check for non-GNU getopt
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+if [ $? != 0 ] ; then echo "W: non-GNU getopt" >&2 ; exit 1 ; fi
 
 eval set -- "$OPTIONS"
 
@@ -68,7 +67,7 @@ for i in /usr/share/initramfs-tools/conf.d/* ${CONFDIR}/conf.d/*; do
 		| grep '^[[:alnum:]][[:alnum:]\._-]*$' | grep -v '\.dpkg-.*$')";
 done
 # FIXME: deprecated those settings on mkinitramfs run
-#        these conf dirs are for boot scripts and land on initramfs
+# 	 these conf dirs are for boot scripts and land on initramfs
 for i in ${EXTRA_CONF}; do
 	if [ -e  ${CONFDIR}/conf.d/${i} ]; then
 		. ${CONFDIR}/conf.d/${i}
@@ -132,25 +131,23 @@ else
 	COMPRESS=${compress}
 fi
 
-if ! command -v ${compress} >/dev/null 2>&1; then
+if ! command -v "${compress}" >/dev/null 2>&1; then
 	compress=gzip
+	COMPRESS=gzip
 	[ "${verbose}" = y ] && \
 		echo "No ${COMPRESS} in ${PATH}, using gzip"
 fi
 
-if [ -r /boot/config-${version} ]; then
-	if ! `grep -q -i config_rd_${COMPRESS}=y /boot/config-${version}` ; then
-		compress=gzip
-		[ "${verbose}" = y ] && \
-			echo "linux-2.6 misses ${COMPRESS} support, using gzip"
-	fi
+if ! `grep -q -i ^config_rd_${COMPRESS%p} /boot/config-${version}` ; then
+	compress=gzip
+	[ "${verbose}" = y ] && \
+		echo "linux-2.6 misses ${COMPRESS} support, using gzip"
 fi
 
-# Always use max compression.
-compress="${compress} -9"
+[ "${compress}" = lzop ] && compress="lzop -9"
 
 if [ -d "${outfile}" ]; then
-	echo "${outfile} is a directory"
+	echo "${outfile} is a directory" >&2
 	exit 1
 fi
 
@@ -166,6 +163,16 @@ fi
 
 DESTDIR="$(mktemp -d ${TMPDIR:-/tmp}/mkinitramfs_XXXXXX)" || exit 1
 chmod 755 "${DESTDIR}"
+
+# do not execute cache_run_scripts() if mounted with noexec
+NOEXEC=""
+if [ -r /etc/mtab ]; then
+	fs=$(df $DESTDIR | tail -1 | awk '{print $6}')
+	if [ -n "$fs" ] && mount | grep -q "on $fs .*noexec" ; then
+		NOEXEC=1
+	fi
+fi
+
 __TMPCPIOGZ="$(mktemp ${TMPDIR:-/tmp}/mkinitramfs-OL_XXXXXX)" || exit 1
 
 DPKG_ARCH=`uname -m`
@@ -191,7 +198,7 @@ done
 # Copy the modules.order file in
 if [ -f "${MODULESDIR}/modules.order" ]; then
 	cp -p "${MODULESDIR}/modules.order" \
-	      "${DESTDIR}${MODULESDIR}/modules.order"
+		"${DESTDIR}${MODULESDIR}/modules.order"
 fi
 
 # MODULES=list case.  Always honour.
@@ -217,26 +224,27 @@ list)
 	# nothing to add
 	;;
 *)
-	echo "mkinitramfs: Warning unsupported MODULES setting: ${MODULES}."
-	echo "mkinitramfs: Falling back to MODULES=most."
+	echo "W: mkinitramfs: unsupported MODULES setting: ${MODULES}."
+	echo "W: mkinitramfs: Falling back to MODULES=most."
 	auto_add_modules
 	;;
 esac
 
 # Have to do each file, because cpio --dereference doesn't recurse down
 # symlinks.
+
 cp -p /usr/share/initramfs-tools/init ${DESTDIR}/init
 
 # add existant boot scripts
 for b in $(cd /usr/share/initramfs-tools/scripts/ && find . \
-	-regextype posix-extended -regex '.*/[[:alnum:]_.]+$' -type f); do
+	-regextype posix-extended -regex '.*/[[:alnum:]\._-]+$' -type f); do
 	[ -d "${DESTDIR}/scripts/$(dirname "${b}")" ] \
 		|| mkdir -p "${DESTDIR}/scripts/$(dirname "${b}")"
 	cp -p "/usr/share/initramfs-tools/scripts/${b}" \
 		"${DESTDIR}/scripts/$(dirname "${b}")/"
 done
 for b in $(cd "${CONFDIR}/scripts" && find . \
-	-regextype posix-extended -regex '.*/[[:alnum:]_.]+$' -type f); do
+	-regextype posix-extended -regex '.*/[[:alnum:]\._-]+$' -type f); do
 	[ -d "${DESTDIR}/scripts/$(dirname "${b}")" ] \
 		|| mkdir -p "${DESTDIR}/scripts/$(dirname "${b}")"
 	cp -p "${CONFDIR}/scripts/${b}" "${DESTDIR}/scripts/$(dirname "${b}")/"
@@ -257,16 +265,29 @@ if [ -n "${ROOT:-}" ]; then
 	echo "ROOT=${ROOT}" > ${DESTDIR}/conf/conf.d/root
 fi
 
+if ! command -v ldd >/dev/null 2>&1 ; then
+	echo "WARNING: no ldd around - install libc-bin" >&2
+	exit 1
+fi
+
+# module-init-tools
+copy_exec /sbin/depmod /sbin
+copy_exec /sbin/modprobe /sbin
+copy_exec /sbin/rmmod /sbin
+mkdir -p "${DESTDIR}/etc/modprobe.d"
+cp -a /etc/modprobe.d/* "${DESTDIR}/etc/modprobe.d/"
+
 run_scripts /usr/share/initramfs-tools/hooks
 run_scripts "${CONFDIR}"/hooks
 
 # cache boot run order
-for b in $(cd "${DESTDIR}/scripts" && find . -mindepth 1 -type d); do
-	cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
-done
-
-# Copy in tsort(1).
-copy_exec /bin/tsort /bin
+if [ -n "$NOEXEC" ]; then
+	echo "W: TMPDIR is mounted noexec, will not cache run scripts."
+else
+	for b in $(cd "${DESTDIR}/scripts" && find . -mindepth 1 -type d); do
+		cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
+	done
+fi
 
 # generate module deps
 depmod -a -b "${DESTDIR}" ${version}
@@ -279,11 +300,8 @@ fi
 
 # Remove any looping or broken symbolic links, since they break cpio.
 [ "${verbose}" = y ] && xargs_verbose="-t"
-find "${DESTDIR}" -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' \
-	| xargs ${xargs_verbose:-} -rL1 rm -f
-
-# Copy resume from klibc
-copy_exec /bin/resume /bin
+(cd "${DESTDIR}" && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' \
+	| xargs ${xargs_verbose:-} -rL1 rm -f)
 
 [ "${verbose}" = y ] && echo "Building cpio ${outfile} initramfs"
 (
@@ -291,19 +309,28 @@ copy_exec /bin/resume /bin
 # cd "${DESTDIR}" && find . | cpio --quiet --dereference -o -H newc | gzip >"${outfile}" || exit 1
 exec 3>&1
 eval `
-    # http://cfaj.freeshell.org/shell/cus-faq-2.html
-    exec 4>&1 >&3 3>&-
-    cd  "${DESTDIR}" 
-    {
-        find . 4>&-; echo "ec1=$?;" >&4
-    } | {
-        cpio --quiet --dereference -o -H newc 4>&-; echo "ec2=$?;" >&4
-    } | ${compress} >"${outfile}"
-    echo "ec3=$?;" >&4
+	# http://cfaj.freeshell.org/shell/cus-faq-2.html
+	exec 4>&1 >&3 3>&-
+	cd  "${DESTDIR}"
+	{
+		find . 4>&-; echo "ec1=$?;" >&4
+	} | {
+		cpio --quiet --dereference -o -H newc 4>&-; echo "ec2=$?;" >&4
+	} | ${compress} >"${outfile}"
+	echo "ec3=$?;" >&4
 `
-if [ "$ec1" -ne 0 ]; then exit "$ec1"; fi
-if [ "$ec2" -ne 0 ]; then exit "$ec2"; fi
-if [ "$ec3" -ne 0 ]; then exit "$ec3"; fi
+if [ "$ec1" -ne 0 ]; then
+	echo "E: mkinitramfs failure find $ec1 cpio $ec2 $compress $ec3"
+	exit "$ec1"
+fi
+if [ "$ec2" -ne 0 ]; then
+	echo "E: mkinitramfs failure cpio $ec2 $compress $ec3"
+	exit "$ec2"
+fi
+if [ "$ec3" -ne 0 ]; then
+	echo "E: mkinitramfs failure $compress $ec3"
+	exit "$ec3"
+fi
 ) || exit 1
 
 if [ -s "${__TMPCPIOGZ}" ]; then
diff --git a/srcpkgs/initramfs-tools/files/update-initramfs b/srcpkgs/initramfs-tools/files/update-initramfs
--- a/srcpkgs/initramfs-tools/files/update-initramfs
+++ b/srcpkgs/initramfs-tools/files/update-initramfs
@@ -131,7 +131,7 @@ backup_booted_initramfs()
 # nuke generated copy
 remove_initramfs_bak()
 {
-	[ -z "${initramfs_bak}" ] && return 0
+	[ -z "${initramfs_bak:-}" ] && return 0
 	rm -f "${initramfs_bak}"
 	verbose "Removing ${initramfs_bak}"
 }
@@ -155,7 +155,7 @@ generate_initramfs()
 			# minversion wasn't met, exit 0
 			exit 0
 		fi
-		echo "update-initramfs: failed for ${initramfs}"
+		echo "update-initramfs: failed for ${initramfs}" >&2
 		exit $mkinitramfs_return
 	fi
 }
@@ -181,7 +181,7 @@ run_bootloader()
 		echo "update-initramfs: please run 'grub-install ${dev}'."
 	fi
 
-	if command -v grub-mkconfig 2>&1 >/dev/null; then
+	if command -v grub-mkconfig >/dev/null 2>&1; then
 		grub-mkconfig -o /boot/grub/grub.cfg
 	fi
 }
@@ -423,7 +423,7 @@ while getopts "k:cudyvtb:h?BV" flag; do
 	b)
 		BOOTDIR="${OPTARG}"
 		if [ ! -d "${BOOTDIR}" ]; then
-			echo "Error: ${BOOTDIR} is not a directory."
+			echo "Error: ${BOOTDIR} is not a directory." >&2
 			exit 1
 		fi
 		;;
@@ -440,7 +440,7 @@ done
 shift $((${OPTIND} - 1))
 
 if [ $# -ne 0 ]; then
-	echo "Invalid argument for option -k."	
+	echo "Invalid argument for option -k." >&2
 	usage
 fi
 
@@ -469,11 +469,8 @@ if [ "${version}" = "all" ] \
 		OPTS="${OPTS} -y"
 	fi
 	for u_version in ${version_list}; do
-		# Don't stop if one version doesn't work.
-		set +e
 		verbose "Execute: ${0} -${mode} -k \"${u_version}\" ${OPTS}"
 		"${0}" -${mode} -k "${u_version}" ${OPTS}
-		set -e
 	done
 	exit 0
 fi
