initramfs-tools: sync with Debian 0.94.4.
Now the version also specifies what Debian version the code uses, i.e
"0.99.debian0.94.4".

--HG--
rename : srcpkgs/initramfs-tools/files/scripts/init-premount/blacklist => srcpkgs/initramfs-tools/files/scripts/init-top/blacklist

diff --git a/srcpkgs/initramfs-tools/files/hook-functions b/srcpkgs/initramfs-tools/files/hook-functions
--- a/srcpkgs/initramfs-tools/files/hook-functions
+++ b/srcpkgs/initramfs-tools/files/hook-functions
@@ -33,8 +33,9 @@ add_modules_from_file()
 		return
 	fi
 
-	sed -e '/^#/d' ${1} | while read module rest; do
-		force_load "${module}" "${rest}"
+	grep '^[^#]' ${1} | while read module args; do
+		[ -n "$module" ] || continue
+		force_load "${module}" "${args}"
 	done
 }
 
@@ -44,7 +45,7 @@ manual_add_modules()
 	local mam_x firmwares firmware
 
 	for mam_x in $(modprobe --set-version="${version}" --ignore-install \
-	--show-depends "${1}" 2>/dev/null | awk '/^insmod/ { print $2 }'); do
+	--quiet --show-depends "${1}" | awk '/^insmod/ { print $2 }'); do
 		# Prune duplicates
 		if [ -e "${DESTDIR}/${mam_x}" ]; then
 			continue
@@ -70,7 +71,12 @@ manual_add_modules()
 			# Only print warning for missing fw of loaded module
 			# or forced loaded module
 			if [ ! -e "/lib/firmware/${firmware}" ] \
-			&& [ ! -e "/lib/firmware/${version}/${firmware}" ]; then
+			&& [ ! -e "/lib/firmware/${version}/${firmware}" ] ; then
+				# Only warn about missing firmware if
+				# /proc/modules exists
+				if [ ! -e /proc/modules ] ; then
+					continue
+				fi
 				if grep -q "^$(basename "${mam_x}" .ko)[[:space:]]" \
 				/proc/modules \
 				|| grep -q "^$(basename "${mam_x}" .ko)" \
@@ -145,6 +151,10 @@ copy_exec() {
 	fi
 
 	# Copy the dependant libraries
+	if ! command -v ldd >/dev/null 2>&1 ; then
+		echo "WARNING: no ldd around - install glibc package."
+		exit 1
+	fi
 	for x in $(ldd ${source} 2>/dev/null | sed -e '
 	    /\//!d;
 	    /linux-gate/d;
@@ -152,8 +162,9 @@ copy_exec() {
 	    s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
 
 		# Try to use non-optimised libraries where possible.
-		# We assume that all HWCAP libraries will be in tls.
-		nonoptlib=$(echo "${x}" | sed -e 's#/lib/\(tls\|i686\).*/\(lib.*\)#/lib/\2#')
+		# We assume that all HWCAP libraries will be in tls,
+		# sse2, vfp or neon.
+		nonoptlib=$(echo "${x}" | sed -e 's#/lib/\(tls\|i686\|sse2\|neon\|vfp\).*/\(lib.*\)#/lib/\2#')
 
 		if [ -e "${nonoptlib}" ]; then
 			x="${nonoptlib}"
@@ -176,14 +187,24 @@ copy_exec() {
 copy_modules_dir()
 {
 	local x_mod
+	local exclude
+	local dir="$1"
+	shift
 
-	if ! [ -d "${MODULESDIR}/${1}" ]; then
+	if ! [ -d "${MODULESDIR}/${dir}" ]; then
 		return;
 	fi
 	if [ "${verbose}" = "y" ]; then
-		echo "Copying module directory ${1}"
+		echo "Copying module directory ${dir}"
+		if [ $# -ge 1 ]; then
+			echo "(excluding $*)"
+		fi
 	fi
-	for x_mod in $(find "${MODULESDIR}/${1}" -name '*.ko' -print); do
+	while [ $# -ge 1 ]; do
+		exclude="$exclude -name $1 -prune -o "
+		shift
+	done
+	for x_mod in $(find "${MODULESDIR}/${dir}" ${exclude} -name '*.ko' -print); do
 		manual_add_modules $(basename ${x_mod} .ko)
 	done
 }
@@ -196,7 +217,7 @@ sys_walk_mod_add()
 	
 	while [ "${device_path}" != "/sys" ]; do
 		sys_walk_modalias ${device_path}
-		driver_path="$(readlink -f ${device_path}/driver)"
+		driver_path="$(readlink -f ${device_path}/driver/module)"
 		if [ -e "$driver_path" ]; then
 			module="$(basename $(readlink -f $driver_path))"
 			if [ -n "${module}" ]; then
@@ -228,10 +249,16 @@ dep_add_modules()
 {
 	local block minor root FSTYPE root_dev_path x
 
+	# require mounted sysfs
+	if [ ! -d /sys/devices/ ]; then
+		echo "mkinitramfs: MODULES dep requires mounted sysfs on /sys"
+		exit 1
+	fi
+
 	# findout root block device + fstype
 	eval "$(mount | awk '/\/dev\// {if ($3 == "/") {print "root=" $1 "\nFSTYPE=" $5; exit}}')"
 	if [ "${root}" = "/dev/root" ] ; then
-		root="/dev/disk/by-uuid/"$(/sbin/blkid -s UUID -o value ${root}) 2>/dev/null
+		root="/dev/disk/by-uuid/"$(blkid -o value -s UUID ${root}) 2>/dev/null
 	fi
 	root="$(readlink -f ${root})"
 
@@ -242,10 +269,13 @@ dep_add_modules()
 
 	# check that fstype rootfs recognition
 	if [ "${FSTYPE}" = "unknown" ]; then
-		echo "mkinitramfs: unknown fstype on root ${root}"
-		echo "mkinitramfs: workaround is MODULES=most" 
-		echo "mkinitramfs: Error please report bug on initramfs-tools" 
+		FSTYPE=$(blkid -o value -s TYPE "${root}")
+		if [  -z "${FSTYPE}" ]; then
+			echo "mkinitramfs: unknown fstype on root ${root}"
+			echo "mkinitramfs: workaround is MODULES=most" 
+			echo "Error please report bug on initramfs-tools"
 		exit 1
+		fi
 	fi
 
 	# Add rootfs
@@ -256,10 +286,10 @@ dep_add_modules()
 		|| [ "${root#/dev/dm-}" != "${root}" ]; then
 		minor=$((0x$(stat --format "%T" ${root}) % 256))
 		block=$(ls -1 /sys/block/dm-${minor}/slaves | head -n 1)
-		# lvm on luks or luks on lvm
-		if [ "${block#dm-}" != "${block}" ]; then
+		# lvm on luks or luks on lvm, possibly lvm snapshots
+		while [ "${block#dm-}" != "${block}" ]; do
 			block=$(ls -1 /sys/block/${block}/slaves | head -n 1)
-		fi
+		done
 		# lvm on md or luks on md
 		if [ "${block#md}" != "${block}" ]; then
 			block=$(awk "/^${block}/{print substr(\$5, 1, 4); exit}" \
@@ -339,6 +369,10 @@ dep_add_modules()
 		manual_add_modules sd_mod
 	fi
 
+	if [ -e /sys/bus/mmc/devices/ ]; then
+		manual_add_modules mmc_block
+	fi
+
 	if [ -e /sys/bus/i2o/devices/ ]; then
 		force_load i2o_block
 		force_load i2o_config
@@ -363,7 +397,7 @@ auto_add_modules()
 {
 	case "$1" in
 	base)
-		for x in ehci-hcd ohci-hcd uhci-hcd usbhid usb-storage ext2 \
+		for x in ehci-hcd ohci-hcd uhci-hcd usbhid btrfs ext2 \
 		ext3 ext4 ext4dev isofs jfs nfs reiserfs udf xfs af_packet \
 		atkbd i8042 virtio_pci; do
 			manual_add_modules "${x}"
@@ -375,19 +409,9 @@ auto_add_modules()
 		done
 	;;
 	net)
-		for x in 3c59x 8139cp 8139too 8390 atl1 atl1e b44 bmac \
-		bnx2 cxgb cxgb3 de2104x de4x5 defxx dl2k dmfe \
-		e100 e1000 e1000e ehea epic100 \
-		ep93xx_eth eql fealnx famachi forcedeth gelic_net \
-		hp100 igb ipg ixgb ixgbe mace mlx4_core mv643xx_eth myri10ge \
-		natsemi ne2k-pci netconsole netxen_nic niu ns83820 \
-		pcnet32 qla3xxx \
-		r8169 s2io sfc sis900 skge sky2 slhc smc911x starfire \
-		sundance sungem sungem_phy sunhme sunvnet tehuti tg3 tlan \
-		tulip typhoon via-rhine via-velocity winbond-840 \
-		xircom_cb xircom_tulip_cb yellowfin; do
-			manual_add_modules "${x}"
-		done
+		copy_modules_dir kernel/drivers/net \
+			appletalk arcnet bonding can hamradio irda pcmcia \
+			tokenring usb wan wimax wireless
 	;;
 	ide)
 		copy_modules_dir kernel/drivers/ide
@@ -427,6 +451,9 @@ auto_add_modules()
 			manual_add_modules "${x}"
 		done
 	;;
+	usb_storage)
+		copy_modules_dir kernel/drivers/usb/storage
+	;;
 	*)
 		auto_add_modules base
 		auto_add_modules kms
@@ -440,10 +467,12 @@ auto_add_modules()
 		auto_add_modules ieee1394
 		auto_add_modules firewire
 		auto_add_modules mmc
+		auto_add_modules usb_storage
 	;;
 	esac
 }
 
+# mkinitramfs help message
 usage()
 {
 	cat >&2 << EOF
@@ -451,15 +480,32 @@ usage()
 Usage: ${0} [OPTION]... -o outfile [version]
 
 Options:
-  -d confdir  Specify an alternative configuration directory.
-  -k          Keep temporary directory used to make the image.
-  -o outfile  Write to outfile.
-  -r root     Override ROOT setting in initramfs.conf.
+  -c compress  Override COMPRESS setting in initramfs.conf.
+  -d confdir   Specify an alternative configuration directory.
+  -k           Keep temporary directory used to make the image.
+  -o outfile   Write to outfile.
+  -r root      Override ROOT setting in initramfs.conf.
 
 See mkinitramfs(8) for further details.
 EOF
 	exit 1
 
+}
+
+# cache boot scripts order
+cache_run_scripts()
+{
+	DESTDIR=${1}
+	scriptdir=${2}
+	initdir=${DESTDIR}${scriptdir}
+	[ ! -d ${initdir} ] && return
+
+	runlist=$(get_prereq_pairs | tsort)
+	for crs_x in ${runlist}; do
+		[ -f ${initdir}/${crs_x} ] || continue
+		echo "${scriptdir}/${crs_x}" >> ${initdir}/ORDER
+		echo "[ -e /conf/param.conf ] && . /conf/param.conf" >> ${initdir}/ORDER
+	done
 }
 
 compare_versions()
diff --git a/srcpkgs/initramfs-tools/files/mkinitramfs b/srcpkgs/initramfs-tools/files/mkinitramfs
--- a/srcpkgs/initramfs-tools/files/mkinitramfs
+++ b/srcpkgs/initramfs-tools/files/mkinitramfs
@@ -9,7 +9,7 @@ CONFDIR="/etc/initramfs-tools"
 verbose="n"
 errors_to="2>/dev/null"
 
-OPTIONS=`getopt -o d:ko:r:v -n "$0" -- "$@"`
+OPTIONS=`getopt -o c:d:ko:r:v -n "$0" -- "$@"`
 
 # Check for non-GNU getopt
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
@@ -18,6 +18,10 @@ eval set -- "$OPTIONS"
 
 while true; do
 	case "$1" in
+	-c)
+		compress="$2"
+		shift 2
+		;;
 	-d)
 		CONFDIR="$2"
 		shift 2
@@ -73,16 +77,6 @@ for i in ${EXTRA_CONF}; do
 	fi
 done
 
-# Handle COMPRESSION_TYPE from initramfs.conf.
-compress_cmd_args="-9"
-
-case "${COMPRESSION_TYPE}" in
-gzip) compress_cmd=gzip;;
-bzip2) compress_cmd=bzip2;;
-lzma) compress_cmd=lzma; compress_cmd_args="$compress_cmd_args -c";;
-*) compress_cmd=gzip;;
-esac
-
 # source package confs
 for i in /usr/share/initramfs-tools/conf-hooks.d/*; do
 	if [ -e "${i}" ]; then
@@ -131,6 +125,27 @@ case "${version}" in
 	;;
 esac
 
+# Check userspace and kernel support for compressed initramfs images
+if [ -z "${compress}" ]; then
+	compress=${COMPRESS}
+else
+	COMPRESS=${compress}
+fi
+
+if ! command -v ${compress} >/dev/null 2>&1; then
+	compress=gzip
+	[ "${verbose}" = y ] && \
+		echo "No ${COMPRESS} in ${PATH}, using gzip"
+fi
+
+if [ -r /boot/config-${version} ]; then
+	if ! `grep -q -i config_rd_${COMPRESS}=y /boot/config-${version}` ; then
+		compress=gzip
+		[ "${verbose}" = y ] && \
+			echo "linux-2.6 misses ${COMPRESS} support, using gzip"
+	fi
+fi
+
 if [ -d "${outfile}" ]; then
 	echo "${outfile} is a directory"
 	exit 1
@@ -139,14 +154,15 @@ fi
 MODULESDIR="/lib/modules/${version}"
 
 if [ ! -e "${MODULESDIR}" ]; then
-	echo "Cannot find ${MODULESDIR}"
-	exit 1
+	echo "WARNING: missing ${MODULESDIR}"
+	echo "Device driver support needs thus be built-in linux image!"
 fi
 if [ ! -e "${MODULESDIR}/modules.dep" ]; then
 	depmod ${version}
 fi
 
 DESTDIR="$(mktemp -t -d mkinitramfs_XXXXXX)" || exit 1
+chmod 755 "${DESTDIR}"
 __TMPCPIOGZ="$(mktemp -t mkinitramfs-OL_XXXXXX)" || exit 1
 
 DPKG_ARCH=`uname -m`
@@ -241,15 +257,28 @@ fi
 run_scripts /usr/share/initramfs-tools/hooks
 run_scripts "${CONFDIR}"/hooks
 
+# cache boot run order
+for b in $(cd "${DESTDIR}/scripts" && find . -mindepth 1 -type d); do
+	cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
+done
+
+# generate module deps
+depmod -a -b "${DESTDIR}" ${version}
+rm -f "${DESTDIR}/lib/modules/${version}"/modules.*map
+
 # Apply DSDT to initramfs
 if [ -e "${CONFDIR}/DSDT.aml" ]; then
 	copy_exec "${CONFDIR}/DSDT.aml" /
 fi
 
+# Remove any looping or broken symbolic links, since they break cpio.
+find "${DESTDIR}" -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' \
+	| xargs -rL1 rm -f
+
 # Copy resume from klibc
 copy_exec /bin/resume /bin
 
-[ "${verbose}" = y ] && echo "Building cpio ${outfile} initramfs (${COMPRESSION_TYPE})"
+[ "${verbose}" = y ] && echo "Building cpio ${outfile} initramfs"
 (
 # work around lack of "set -o pipefail" for the following pipe:
 # cd "${DESTDIR}" && find . | cpio --quiet --dereference -o -H newc | gzip >"${outfile}" || exit 1
@@ -262,7 +291,7 @@ eval `
         find . 4>&-; echo "ec1=$?;" >&4
     } | {
         cpio --quiet --dereference -o -H newc 4>&-; echo "ec2=$?;" >&4
-    } | ${compress_cmd} ${compress_cmd_args} >"${outfile}"
+    } | ${compress} >"${outfile}"
     echo "ec3=$?;" >&4
 `
 if [ "$ec1" -ne 0 ]; then exit "$ec1"; fi
diff --git a/srcpkgs/initramfs-tools/files/scripts/functions b/srcpkgs/initramfs-tools/files/scripts/functions
--- a/srcpkgs/initramfs-tools/files/scripts/functions
+++ b/srcpkgs/initramfs-tools/files/scripts/functions
@@ -42,8 +42,8 @@ panic()
 	fi
 	modprobe i8042
 	modprobe atkbd
-	echo $@
-	PS1='(initramfs) ' /bin/sh -i </dev/console >/dev/console 2>&1
+	echo "$@"
+	REASON="$@" PS1='(initramfs) ' /bin/sh -i </dev/console >/dev/console 2>&1
 }
 
 maybe_break()
@@ -179,9 +179,22 @@ reduce_prereqs()
 	done
 }
 
+get_prereq_pairs()
+{
+	set_initlist
+	for gp_x in ${initlist}; do
+		echo ${gp_x} ${gp_x}
+		prereqs=$(${initdir}/${gp_x} prereqs)
+		for prereq in ${prereqs}; do
+			echo ${prereq} ${gp_x}
+		done
+	done
+}
+
 call_scripts()
 {
 	for cs_x in ${runlist}; do
+		[ -f ${initdir}/${cs_x} ] || continue
 		# mkinitramfs verbose output
 		if [ "${verbose}" = "y" ]; then
 			echo "Calling hook ${cs_x}"
@@ -198,9 +211,17 @@ run_scripts()
 {
 	initdir=${1}
 	[ ! -d ${initdir} ] && return
-	get_prereqs
-	reduce_prereqs
-	call_scripts
+
+	if [ -f ${initdir}/ORDER ]; then
+		. ${initdir}/ORDER
+	elif command -v tsort >/dev/null 2>&1; then
+		runlist=$(get_prereq_pairs | tsort)
+		call_scripts $2
+	else
+		get_prereqs
+		reduce_prereqs
+		call_scripts
+	fi
 }
 
 # Load custom modules first
@@ -249,40 +270,114 @@ parse_numeric() {
 	ROOT=/dev/root
 }
 
+# Parameter: device node to check
+# Echos fstype to stdout
+# Return value: indicates if an fs could be recognized
+get_fstype ()
+{
+	local FS FSTYPE FSSIZE RET
+	FS="${1}"
+
+	# vol_id has a more complete list of file systems,
+	# but fstype is more robust
+	eval $(fstype "${FS}" 2> /dev/null)
+	if [ "$FSTYPE" = "unknown" ] &&  command -v blkid >/dev/null 2>&1 ; then
+		FSTYPE=$(blkid -o value -s TYPE "${FS}")
+	elif [ "$FSTYPE" = "unknown" ] && [ -x /lib/udev/vol_id ]; then
+		FSTYPE=$(/lib/udev/vol_id -t "${FS}" 2> /dev/null)
+	fi
+	RET=$?
+
+	if [ -z "${FSTYPE}" ]; then
+		FSTYPE="unknown"
+	fi
+
+	echo "${FSTYPE}"
+	return ${RET}
+}
+
 configure_networking()
 {
+	if [ -n "${BOOTIF}" ]; then
+		# pxelinux sets BOOTIF to a value based on the mac address of the
+		# network card used to PXE boot, so use this value for DEVICE rather
+		# than a hard-coded device name from initramfs.conf. this facilitates
+		# network booting when machines may have multiple network cards.
+		# pxelinux sets BOOTIF to 01-$mac_address
+
+		# strip off the leading "01-", which isn't part of the mac
+		# address
+		temp_mac=${BOOTIF#*-}
+
+		# convert to typical mac address format by replacing "-" with ":"
+		bootif_mac=""
+		IFS='-'
+		for x in $temp_mac ; do
+			if [ -z "$bootif_mac" ]; then
+				bootif_mac="$x"
+			else
+				bootif_mac="$x:$bootif_mac"
+			fi
+		done
+		unset IFS
+
+		# look for devices with matching mac address, and set DEVICE to
+		# appropriate value if match is found.
+		for device in /sys/class/net/* ; do
+			if [ -f "$device/address" ]; then
+				current_mac=$(cat "$device/address")
+				if [ "$bootif_mac" = "$current_mac" ]; then
+					DEVICE=${device##*/}
+					break
+				fi
+			fi
+		done
+	fi
+
 	# networking already configured thus bail out
 	[ -n "${DEVICE}" ] && [ -e /tmp/net-"${DEVICE}".conf ] && return 0
 
 	# support ip options see linux sources
 	# Documentation/filesystems/nfsroot.txt
-	case ${IP} in
-	none|off)
-		# Do nothing
-		;;
-	""|on|any)
-		# Bring up device
-		ipconfig -t 180 ${DEVICE}
-		;;
-	dhcp|bootp|rarp|both)
-		ipconfig -t 180 -c ${IP} -d ${DEVICE}
-		;;
-	*)
-		ipconfig -t 180 -d $IP
+	# Documentation/frv/booting.txt
 
-		# grab device entry from ip option
-		NEW_DEVICE=${IP#*:*:*:*:*:*}
-		if [ "${NEW_DEVICE}" != "${IP}" ]; then
-			NEW_DEVICE=${NEW_DEVICE%:*}
-		else
-			# wrong parse, possibly only a partial string
-			NEW_DEVICE=
+	for ROUNDTTT in 2 3 4 6 9 16 25 36 64 100; do
+
+		# The NIC is to be configured if this file does not exist.
+		# Ip-Config tries to create this file and when it succeds
+		# creating the file, ipconfig is not run again.
+		if [ -e /tmp/net-"${DEVICE}".conf ]; then
+			break;
 		fi
-		if [ -n "${NEW_DEVICE}" ]; then
-			DEVICE="${NEW_DEVICE}"
-		fi
-		;;
-	esac
+
+		case ${IP} in
+		none|off)
+			# Do nothing
+			;;
+		""|on|any)
+			# Bring up device
+			ipconfig -t ${ROUNDTTT} ${DEVICE}
+			;;
+		dhcp|bootp|rarp|both)
+			ipconfig -t ${ROUNDTTT} -c ${IP} -d ${DEVICE}
+			;;
+		*)
+			ipconfig -t ${ROUNDTTT} -d $IP
+
+			# grab device entry from ip option
+			NEW_DEVICE=${IP#*:*:*:*:*:*}
+			if [ "${NEW_DEVICE}" != "${IP}" ]; then
+				NEW_DEVICE=${NEW_DEVICE%:*}
+			else
+				# wrong parse, possibly only a partial string
+				NEW_DEVICE=
+			fi
+			if [ -n "${NEW_DEVICE}" ]; then
+				DEVICE="${NEW_DEVICE}"
+			fi
+			;;
+		esac
+	done
 
 	# source ipconfig output
 	if [ -n "${DEVICE}" ]; then
@@ -297,6 +392,6 @@ configure_networking()
 # Wait for queued kernel/udev events
 wait_for_udev()
 {
-	[ -x "$(command -v udevadm)" ] || return 0
+	command -v udevadm >/dev/null 2>&1 || return 0
 	udevadm settle ${1:+--timeout=$1}
 }
