php: update to 8.0.0

diff --git a/srcpkgs/php/template b/srcpkgs/php/template
--- a/srcpkgs/php/template
+++ b/srcpkgs/php/template
@@ -1,7 +1,7 @@
 # Template file for 'php'
 pkgname=php
-version=7.4.11
-revision=2
+version=8.0.0
+revision=1
 hostmakedepends="bison pkg-config apache-devel"
 makedepends="apache-devel enchant-devel freetds-devel freetype-devel gdbm-devel
  gmp-devel libcurl-devel libjpeg-turbo-devel libmysqlclient-devel
@@ -13,7 +13,7 @@ maintainer="Steve Prybylski <sa.prybylx@gmail.com>"
 license="PHP-3.01"
 homepage="https://www.php.net"
 distfiles="http://www.php.net/distributions/php-${version}.tar.xz"
-checksum=5d31675a9b9c21b5bd03389418218c30b26558246870caba8eb54f5856e2d6ce
+checksum=b5278b3eef584f0c075d15666da4e952fa3859ee509d6b0cc2ed13df13f65ebb
 
 conf_files="/etc/php/php.ini"
 
@@ -180,10 +180,10 @@ php-cgi_package() {
 php-apache_package() {
 	short_desc+=' - Apache SAPI'
 	depends="php-${version}_${revision}"
-	conf_files="/etc/apache/extra/php7_module.conf"
+	conf_files="/etc/apache/extra/php8_module.conf"
 	pkg_install() {
-		vinstall ${wrksrc}/build-apache/libs/libphp7.so 755 usr/libexec/httpd/modules
-		vinstall ${FILESDIR}/apache.conf 644 etc/apache/extra php7_module.conf
+		vinstall ${wrksrc}/build-apache/libs/libphp.so 755 usr/libexec/httpd/modules
+		vinstall ${FILESDIR}/apache.conf 644 etc/apache/extra php8_module.conf
 	}
 }
 
@@ -219,6 +219,15 @@ php-pear_package() {
 		if [ -n "$CROSS_BUILD" ]; then
 			_env+=" PEAR_PHP=/usr/bin/php"
 		fi
+		# Open bug since July, hacky fix
+		# Bug: https://bugs.php.net/bug.php?id=79869
+		# Proposed fix: https://github.com/pear/PHP_Archive/pull/4
+
+		# This will download the pear installer but ultimately fail because of syntax errors
+		make install-pear ${_env} || true;
+		# Patch the syntax error and remove some spaces to keep the length the same and the zip valid
+		sed -i 's: \$flags \& 0x00010000:\$flags[1]\&0x00010000:' pear/install-pear-nozlib.phar
+
 		make install-pear ${_env}
 		rm -rf ${PKGDESTDIR}/.{channels,depdb,depdblock,filemap,lock,registry}
 		rm -rf ${PKGDESTDIR}/usr/share/pear/.{channels,depdb,depdblock,filemap,lock,registry}
