subversion-kwallet-auth: fix ftbfs

diff --git a/srcpkgs/subversion-kwallet-auth/patches/kwallet6.patch b/srcpkgs/subversion-kwallet-auth/patches/kwallet6.patch
--- a/srcpkgs/subversion-kwallet-auth/patches/kwallet6.patch
+++ b/srcpkgs/subversion-kwallet-auth/patches/kwallet6.patch
@@ -86,3 +86,44 @@
    fi
  
    CXXMODEFLAGS="$CXXFLAGS"
+--- a/autogen.sh
++++ b/autogen.sh
+@@ -180,38 +180,6 @@ if test -z "$PYTHON"; then
+ fi
+ export PYTHON
+ 
+-# Compile SWIG headers into standalone C files if we are in release mode
+-if test -n "$RELEASE_MODE"; then
+-  echo "Generating SWIG code..."
+-  # Generate build-outputs.mk in non-release-mode, so that we can
+-  # build the SWIG-related files
+-  "$PYTHON" ./gen-make.py build.conf || gen_failed=1
+-
+-  # Build the SWIG-related files
+-  make -f autogen-standalone.mk autogen-swig || gen_failed=1
+-
+-  # Remove the .swig_*checked files
+-  rm -f .swig_checked .swig_pl_checked .swig_py_checked .swig_rb_checked
+-fi
+-
+-if test -n "$SKIP_DEPS"; then
+-  echo "Creating build-outputs.mk (no dependencies)..."
+-  "$PYTHON" ./gen-make.py $RELEASE_ARGS -s build.conf || gen_failed=1
+-else
+-  echo "Creating build-outputs.mk..."
+-  "$PYTHON" ./gen-make.py $RELEASE_ARGS build.conf || gen_failed=1
+-fi
+-
+-if test -n "$RELEASE_MODE"; then
+-  find build/ -name '*.pyc' -exec rm {} \;
+-fi
+-
+-rm autogen-standalone.mk
+-
+-if test -n "$gen_failed"; then
+-  echo "ERROR: gen-make.py failed"
+-  exit 1
+-fi
+ 
+ # Produce config.h.in
+ echo "Creating svn_private_config.h.in..."
