Fixed linting issues

diff --git a/srcpkgs/brave/INSTALL b/srcpkgs/brave/INSTALL
--- a/srcpkgs/brave/INSTALL
+++ b/srcpkgs/brave/INSTALL
@@ -4,27 +4,27 @@
 _BUILDDIR="/tmp/brave.build"
 
 if test "$ACTION" = "post"; then
-  . /usr/share/brave/pkgdata
-  mkdir -p "$_BUILDDIR"
-  (
-    set -e
-    cd "$_BUILDDIR"
-    xbps-uhelper fetch "https://github.com/brave/brave-browser/releases/download/v${SVERSION}/brave-v${SVERSION}-linux-${SARCH}.zip"
-    echo "${SCHECKSUM}  brave-v${SVERSION}-linux-${SARCH}.zip" >checksum
-    sha256sum -c checksum
-    unzip -q "brave-v${SVERSION}-linux-${SARCH}.zip"
-    rm "brave-v${SVERSION}-linux-${SARCH}.zip"
-  )
-  if [ $? -ne 0 ] ; then
-    echo "Failed downloading brave"
-    rm -r "$_BUILDDIR";
-    exit 1;
-  fi
+	. /usr/share/brave/pkgdata
+	mkdir -p "$_BUILDDIR"
+	(
+		set -e
+		cd "$_BUILDDIR"
+		xbps-uhelper fetch "https://github.com/brave/brave-browser/releases/download/v${SVERSION}/brave-v${SVERSION}-linux-${SARCH}.zip"
+		echo "${SCHECKSUM}  brave-v${SVERSION}-linux-${SARCH}.zip" >checksum
+		sha256sum -c checksum
+		unzip -q "brave-v${SVERSION}-linux-${SARCH}.zip"
+		rm "brave-v${SVERSION}-linux-${SARCH}.zip"
+	)
+	if [ $? -ne 0 ] ; then
+		echo "Failed downloading brave"
+		rm -r "$_BUILDDIR";
+		exit 1;
+	fi
 
-  mkdir -p /usr/share/brave
-  cp -r ${_BUILDDIR}/* /usr/share/brave/
-  ln -sf "/usr/share/brave/brave" /bin/
-  ln -sf "/usr/share/brave/brave.desktop" /usr/share/applications/
-  rm -r $_BUILDDIR
+	mkdir -p /usr/share/brave
+	cp -r ${_BUILDDIR}/* /usr/share/brave/
+	ln -sf "/usr/share/brave/brave" /bin/
+	ln -sf "/usr/share/brave/brave.desktop" /usr/share/applications/
+	rm -r $_BUILDDIR
 fi
 
