qt6-base: update to 6.7.2.

diff --git a/srcpkgs/qt6-base/template b/srcpkgs/qt6-base/template
--- a/srcpkgs/qt6-base/template
+++ b/srcpkgs/qt6-base/template
@@ -1,7 +1,9 @@
 # Template file for 'qt6-base'
+#
+# On update rebuild all pkg with qt6-base-private-devel
 pkgname=qt6-base
-version=6.6.0
-revision=2
+version=6.7.2
+revision=1
 build_style=cmake
 configure_args="-DINSTALL_DATADIR=share/qt6
  -DINSTALL_ARCHDATADIR=lib${XBPS_TARGET_WORDSIZE}/qt6
@@ -13,12 +15,13 @@ configure_args="-DINSTALL_DATADIR=share/qt6
  -DINSTALL_SYSCONFDIR=/etc/xdg
  -DQT_FEATURE_openssl_linked=ON
  -DQT_FEATURE_system_sqlite=ON
+ -DQT_FEATURE_system_xcb_xinput=ON
  -DQT_FEATURE_libproxy=ON
  -DQT_FEATURE_qmake=ON
  -DBUILD_WITH_PCH=OFF"
 hostmakedepends="perl pkg-config xmlstarlet"
 makedepends="zlib-devel libzstd-devel dbus-devel libmd4c-devel
- double-conversion-devel glib-devel libxcb-devel
+ double-conversion-devel glib-devel libxcb-devel libSM-devel
  xcb-util-image-devel xcb-util-keysyms-devel
  xcb-util-renderutil-devel xcb-util-wm-devel
  MesaLib-devel pcre2-devel icu-devel mtdev-devel harfbuzz-devel
@@ -32,7 +35,7 @@ maintainer="John <me@johnnynator.dev>"
 license="GPL-3.0-only WITH Qt-GPL-exception-1.0, LGPL-3.0-only, GPL-2.0-or-later"
 homepage="https://www.qt.io"
 distfiles="https://download.qt.io/official_releases/qt/${version%.*}/${version}/submodules/qtbase-everywhere-src-${version}.tar.xz"
-checksum=039d53312acb5897a9054bd38c9ccbdab72500b71fdccdb3f4f0844b0dd39e0e
+checksum=c5f22a5e10fb162895ded7de0963328e7307611c688487b5d152c9ee64767599
 python_version=3
 
 if [ "$CROSS_BUILD" ]; then
@@ -45,6 +48,12 @@ fi
 if [ "$XBPS_CHECK_PKGS" ]; then
 	configure_args+=" -DQT_BUILD_TESTS=ON"
 fi
+
+subpackages="qt6-concurrent qt6-core qt6-dbus qt6-gui qt6-network
+ qt6-opengl-widgets qt6-plugin-mysql qt6-plugin-networkinformation
+ qt6-plugin-odbc qt6-plugin-pgsql qt6-plugin-sqlite qt6-plugin-tls-openssl
+ qt6-plugin-tls-qcertonly qt6-printsupport qt6-sql qt6-test qt6-widgets qt6-xml
+ qt6-base-private-devel qt6-base-doc qt6-base-devel"
 
 do_check() {
 	cd build
@@ -70,6 +79,11 @@ do_check() {
 	failing_tests+=" mockplugins test_import_plugins
 	 test_static_resources test_generating_cpp_exports"
 	failing_tests+=" tst_qstorageinfo"
+	# cmake
+	failing_tests+=" test_qt_add_resources_rebuild test_collecting_plugins
+	 test_standalone_test test_qt_extract_metatypes"
+	# Failing readonly and out-of-memory
+	failing_tests+=" tst_qsharedmemory"
 	if [ "$XBPS_TARGET_LIBC" = musl ]; then
 		# Some glibc specific DNS Lookup
 		failing_tests+=" tst_qdnslookup"
@@ -257,6 +271,21 @@ qt6-plugin-networkinformation_package() {
 	short_desc+=" - NetworkInformation plugin"
 	pkg_install() {
 		vmove usr/lib/qt6/plugins/networkinformation
+	}
+}
+
+qt6-base-private-devel_package() {
+	short_desc+=" - private development files"
+	depends="qt6-base-devel>=${version}_${revision}"
+	pkg_install() {
+		for dir in $(cd ${DESTDIR} && pwd >&2 && find usr/include -type d -name private); do
+			vmove "$dir"
+		done
+		vmove "usr/lib/cmake/*Private"
+		vmove "usr/lib/qt6/metatypes/*private_*_metatypes.json"
+		# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921930
+		# vmove "usr/lib/qt6/mkspecs/modules/*_private.pri"
+		vmove "usr/lib/qt6/modules/*Private.json"
 	}
 }
 
