cross-arm-none-eabi: update to 0.27 (gcc-8.2.0)

diff --git a/srcpkgs/cross-arm-none-eabi/files/enable-with-multilib-list-for-arm.patch b/srcpkgs/cross-arm-none-eabi/files/enable-with-multilib-list-for-arm.patch
--- a/srcpkgs/cross-arm-none-eabi/files/enable-with-multilib-list-for-arm.patch
+++ b/srcpkgs/cross-arm-none-eabi/files/enable-with-multilib-list-for-arm.patch
@@ -29,42 +29,26 @@ index b8bb4d65825..713e35b62af 100644
  	  use_gcc_stdint=wrap
  	  ;;
  	arm*-*-fuchsia*)
-@@ -3787,56 +3787,6 @@ case "${target}" in
- 			echo "Switch \"--with-tune\" may not be used with switch \"--with-cpu\""  1>&2
+@@ -3899,43 +3899,6 @@
  			exit 1
  		fi
--
+ 
 -		# Add extra multilibs
 -		if test "x$with_multilib_list" != x; then
 -			arm_multilibs=`echo $with_multilib_list | sed -e 's/,/ /g'`
--			case ${arm_multilibs} in
--			aprofile)
--				# Note that arm/t-aprofile is a
--				# stand-alone make file fragment to be
--				# used only with itself.  We do not
--				# specifically use the
--				# TM_MULTILIB_OPTION framework because
--				# this shorthand is more
--				# pragmatic.
--				tmake_profile_file="arm/t-aprofile"
--				;;
--			rmprofile)
--				# Note that arm/t-rmprofile is a
--				# stand-alone make file fragment to be
--				# used only with itself.  We do not
--				# specifically use the
--				# TM_MULTILIB_OPTION framework because
--				# this shorthand is more
--				# pragmatic.
--				tmake_profile_file="arm/t-rmprofile"
--				;;
--			default)
--				;;
--			*)
--				echo "Error: --with-multilib-list=${with_multilib_list} not supported." 1>&2
--				exit 1
--				;;
--			esac
+-			if test "x${arm_multilibs}" != xdefault ; then
+-				for arm_multilib in ${arm_multilibs}; do
+-					case ${arm_multilib} in
+-					aprofile|rmprofile)
+-						tmake_profile_file="arm/t-multilib"
+-						;;
+-					*)
+-						echo "Error: --with-multilib-list=${with_multilib_list} not supported." 1>&2
+-						exit 1
+-						;;
+-					esac
+-				done
+-			fi
 -
 -			if test "x${tmake_profile_file}" != x ; then
 -				# arm/t-aprofile and arm/t-rmprofile are only
@@ -79,13 +63,16 @@ index b8bb4d65825..713e35b62af 100644
 -				    echo "Error: You cannot use any of --with-arch/cpu/fpu/float/mode with --with-multilib-list=${with_multilib_list}" 1>&2
 -				    exit 1
 -				fi
--
+-				# But pass the default value for float-abi
+-				# through to the multilib selector
+-				with_float="soft"
 -				tmake_file="${tmake_file} ${tmake_profile_file}"
+-				TM_MULTILIB_CONFIG="$with_multilib_list"
 -			fi
 -		fi
+ 		target_cpu_cname=${target_cpu_cname:-arm6}
+ 		with_cpu=${with_cpu:-$target_cpu_cname}
  		;;
- 
- 	fr*-*-*linux*)
 diff --git a/gcc/config/arm/t-mlibs b/gcc/config/arm/t-mlibs
 new file mode 100644
 index 00000000000..5720cf7503d
